### ISSUE TITLE
ci: Аutomate Nightly - Release builds with GitHub actions

### ISSUE THREAD

**Issue by 0xMRTT** [GradienceTeam/Gradience#107]
### Discussed in https://github.com/orgs/AdwCustomizerTeam/discussions/76

<div type='discussions-op-text'>

<sup>Originally posted by **daudix-UFO** August  9, 2022</sup>
With GitHub actions we can generate nightly builds automaticly on pushes, this will help new users install the app without need in building it

I have started working on it in my fork, here you can test it and make changes: https://github.com/daudix-UFO/AdwCustomizer/actions

Little To-Do:

- [x] Fix not working actions
- [ ] Fix locales not working
- [x] Setup correct building environment
- [x] Setup build of aarch64 version
- [x] Automate Nightly versions on pushes
- [ ] Automate build of releases
- [ ] Generate release notes
- [ ] Publish releases on Flathub</div>

**Comment by daudix-UFO** [comment]
Possile solution for not working locales is generating flatpak bundle with a `.Locale`

https://github.com/flatpak/flatpak-github-actions/issues/46

**Comment by daudix-UFO** [comment]
As we need to change the logic of nightly builds, I close this issue for now (locales problem is everywhere, so this is OK)
