### ISSUE TITLE
Publish on flathub

### ISSUE THREAD

**Issue by AndroGR** [GradienceTeam/Gradience#112]
### Discussed in https://github.com/orgs/AdwCustomizerTeam/discussions/110

<div type='discussions-op-text'>

<sup>Originally posted by **0xMRTT** August 12, 2022</sup>
Follow the flathub submission guidelines and add required files on com.github.AdwCustomizerTeam.AdwCustomizer . Then merge against merge-pr</div>

I open this as an issue because almost everyone expects Flatpaks to be in Flathub. I'll take a look when ready.

**Comment by ArtyIF** [comment]
This project is using GNOME Platform 43, which isn't stable yet. It will be stable in September apparently. Flathub doesn't allow any unstable packages in their repositories. Downgrading to Platform 42 will probably be hard as the project uses AdwMessageDialog, which has a different API than GtkMessageDialog.

**Comment by 0xMRTT** [comment]
We also need to found a ne name #113

**Comment by AndroGR** [comment]
@ArtyIF We can prepare the ground for now, and publish it once ready to do so. After all I still can't get my screenshots to work properly on GNOME Software.

**Comment by AndroGR** [comment]
Also @0xMRTT this is supposed to go in 0.3 at least. Remove the tag.

**Comment by AdwCustomizer** [comment]
See #101 

> @ArtyIF We can prepare the ground for now, and publish it once ready to do so. After all I still can't get my screenshots to work properly on GNOME Software.

**Comment by daudix-UFO** [comment]
I know how to fix screenshots, will do it soon

**Comment by 0xMRTT** [comment]
If you wanna make screenshot, use the latest flatpak nightly from Github actions or build flatpak yourself using: `flatpak-builder --install --user --force-clean repo/ com.github.AdwCustomizerTeam.AdwCustomizer.Devel.json`

**Comment by daudix-UFO** [comment]
Updates screenshots and URL in appdata, can someone test this?

**Comment by AndroGR** [comment]
Works fine on GNOME Software @daudix-UFO

**Comment by daudix-UFO** [comment]
Can we publish it in Flathub Beta or GNOME-Nightly?

**Comment by daudix-UFO** [comment]
https://discourse.flathub.org/t/how-to-use-flathub-beta/2111

**Comment by daudix-UFO** [comment]
What about AdwMessageDialog?

**Comment by daudix-UFO** [comment]
ArtyIF said 2 days ago that it not merged in stable GNOME platform

**Comment by daudix-UFO** [comment]
Yes, and we will have some time (2+ weeks) to finish v0.2.0 with new Monet engine and Plugins support!

**Comment by daudix-UFO** [comment]
Also we need to remove unused app permissions

**Comment by daudix-UFO** [comment]
Also maybe this is a solution for not working material you

**Comment by AndroGR** [comment]
Generally the flatpak permission model is not the most secure one. The most you get is a warning in your GUI app store and nothing more. It would be better if it had some dynamic pemission model, where it asks for permissions through some system API. Yes, I know `--sandbox` exists, but aren't flatpaks supposed to be user friendly and not run from the command line?

**Comment by daudix-UFO** [comment]
Gradience available on Flathub :tada:
