### ISSUE TITLE
feat: add backups 

### ISSUE THREAD

**Issue by 0xMRTT** [GradienceTeam/Gradience#119]
### Feature description

Currently when user apply a preset, gtk.css is overwritten with the new config.

I propose to add a begin and end balise. And when user apply on a preset, it will just replace the content between balises

### Self-service

- [X] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/AdwCustomizerTeam/community/blob/main/CONTRIBUTING_GUIDELINES.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/AdwCustomizerTeam/community/blob/main/CODE_OF_CONDUCT.md).

**Comment by DivineBicycle** [comment]
We could also backup ```gtk.css``` to ```gtk.css.backup```? Then when reverting changes we could restore that file? Might be a bit more work though. If I figure out #284 and how .po files work I could try to implement this.

**Comment by DivineBicycle** [comment]
Keyword there is try ;)

**Comment by DivineBicycle** [comment]
Does this pull request work? #301

**Comment by 0xMRTT** [comment]
My idea was to add a kind of open and end tag. And Gradience will only write between tags, so the user can do the rest manually

**Comment by DivineBicycle** [comment]
Hm, that sounds like a good idea, but does it possibly add complexity?

**Comment by 0xMRTT** [comment]
Your idea is perfect it's like package manager with `.pacnew`

**Comment by DivineBicycle** [comment]
> Your idea is perfect it's like package manager with .pacnew

Yes, that's what I was thinking of haha
