### ISSUE TITLE
Toast says preset applied but nothing happens

### ISSUE THREAD

**Issue by abuhuraira0099** [GradienceTeam/Gradience#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I installed the app from the latest flatpak release. I made a preset and pressed the apply button and set the theme. A toast message said that the preset was applied. But it did not change anything. Both Libadwaita and adw-gtk3 apps remained as before. I tried it again and again. I tried logging out and in again, but it did not help. I have set permissions for both GTK4 and GTK3 according to the guidance from the Readme page. I also have the Nightly SDK build installed. I also tried deleting the GTK4 config files. I can't figure out what I am missing here.

### To Reproduce

1. Login on a Fedora Workstation 37 Gnome wayland session.
2. Follow the steps from the readme page.
3. Download and install the latest Flatpak build from the release page.
4. Apply a preset to change Libadwaita and adw-gtk3 colors.

### Expected behavior

The theme colors should be changed according to my preset. But it did not.

### OS

Fedora Linux 37 (Workstation Edition)

### Version

0.1.0

### Installation method

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdwCustomizer** [comment]
Welcome on Adwaita Manager. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible.

**Comment by LyesSaadi** [comment]
Same when building from source on Fedora Rawhide (so 37 for now).

**Comment by LyesSaadi** [comment]
Didn't apply at all. Did check the Apply as Dark Theme. `make local` fails to apply anything as well. I get nothing in the terminal logs.

**Comment by LyesSaadi** [comment]
Indeed ! Thanks ! You can close this !

**Comment by abuhuraira0099** [comment]
> Is the change applied on gtk4+libadwaita apps only or didn't apply at all ?

Mine did not apply at all.

**Comment by abuhuraira0099** [comment]
> When applied the preset, did you checked apply as dark theme if you are using the dark theme ?

I tried both with the button enabled and disabled. I also tried changing the global from the Gnome quick settings.

**Comment by abuhuraira0099** [comment]
> Which version are you using ?

I am now trying with 0.1.0 built it with flatpak-build command. I can't couldn't compile with meson as it says I don't have the blueprint dependency. I couldn't find a package for this in the fedora or rpmfusion repo. I tried running the pip install... command from the readme to install deps, but it said all deps are installed. I don't know what to do.

**Comment by abuhuraira0099** [comment]
> But with which version did you tried the first time?

It was the prebuilt Flatpak from the 0.1.0 release page. They have minor UI differences, but none of them are working.

**Comment by abuhuraira0099** [comment]
Can you please refer to which build I should try? I tried [48ca2c1](https://github.com/AdwCustomizerTeam/AdwCustomizer/commit/48ca2c168c8b0cca3d465c5948ec9b83be8b6333) right now, but it's still not working.

**Comment by abuhuraira0099** [comment]
> Sorry,but I can't do anything for now. I'll try to improve GitHub CI soon.
> 
> (The only way is to build from sources)

Take your time. It's not something super important. I guess I will wait for now. I was excited to try it though.

**Comment by daudix-UFO** [comment]
I reopen it for now

**Comment by daudix-UFO** [comment]
In my system everything works in latest build

**Comment by abuhuraira0099** [comment]
> In my system everything works in latest build

Okay I will try and report it back.

**Comment by abuhuraira0099** [comment]
> Okay I will try and report it back.

Still no success. I guess something is wrong at my setup. But other theming method (like Material You Theme extension and adw-colors) work fine.

**Comment by 0xMRTT** [comment]
I think that's related to Flatpak

**Comment by abuhuraira0099** [comment]
> I think that's related to Flatpak

Here is my flatpak filesystem permission ss:
![Screenshot from 2022-08-17 11-22-07](https://user-images.githubusercontent.com/79898595/185041128-82899979-1368-4f0e-960b-8f826aeeeaed.png)

**Comment by 0xMRTT** [comment]
Tried with a local Flatpak build and it works
