### ISSUE TITLE
Improve the GTK 3 warning icon

### ISSUE THREAD

**Issue by ArtyIF** [GradienceTeam/Gradience#14]
Currently it's just a warning icon, and its purpose only pops up when you click on it. It needs to be changed to something clearer. IMO it should be something like the GTK cube with a 3 on or next to it. Unfortunately, I'm not good with Inkscape, so some help will be needed.

@daudix-UFO maybe?

**Comment by daudix-UFO** [comment]
Of course, will make a few versions soon ;)

**Comment by daudix-UFO** [comment]
BTW, I tried to make an icon for adw-gtk3, and it looks like your description

![adw-gtk3](https://user-images.githubusercontent.com/77155297/180670132-732e2a6d-3a58-4c38-9be0-21b3b8a963b4.svg)

_It's 20 days old, maybe I need to suggest it now?_

**Comment by daudix-UFO** [comment]
Somthing like this:

First have normal "3" (8pt), and second a bit bigger (9pt)

![Снимок экрана от 2022-07-25 03-30-50](https://user-images.githubusercontent.com/77155297/180672654-5e1925c9-5089-4665-822c-9ba8eb997faa.png)
![Снимок экрана от 2022-07-25 03-30-41](https://user-images.githubusercontent.com/77155297/180672656-9af28ce5-e33d-4d5c-baf4-bc32ce42b38b.png)

**Comment by ArtyIF** [comment]
I think the 3 is the wrong font, it should be similar to the "a" in the symbolic preview (second row, second/third from the left)

**Comment by ArtyIF** [comment]
My idea would be something like this:

![image](https://user-images.githubusercontent.com/8017858/180739929-d1d7501c-f352-4dbc-bcb2-e893ba876c8c.png)

**Comment by ArtyIF** [comment]
First option is good, but the cube would look better if it were wireframe and the bottom right corner of the 3 was also rounded.

**Comment by daudix-UFO** [comment]
It based on a GTK4 DEMO app icon

**Comment by daudix-UFO** [comment]
> First option is good, but the cube would look better if it were wireframe and the bottom right corner of the 3 was also rounded.

Will do this RN

**Comment by daudix-UFO** [comment]
Somthing lie this?

![Alpha](https://user-images.githubusercontent.com/77155297/180888229-0217cd62-99c7-47d7-b81f-c7ada8879f4b.png)

**Comment by daudix-UFO** [comment]
Wireframe version

[📎 SVG](https://user-images.githubusercontent.com/77155297/180890304-d837ddaa-cf36-448a-9797-59e0993c7c16.svg)

[📎 Source](https://user-images.githubusercontent.com/77155297/180890344-c4f15bfb-a1e2-4cc2-b886-1b3d948dc397.svg)

![Alpha-Wireframe](https://user-images.githubusercontent.com/77155297/180890378-af520d17-63d8-4475-a59c-a8693b13414e.png)

**Comment by ArtyIF** [comment]
Merge the cube sides (it's a cube), make the middle stick in the 3 shorter, and I guess add a notch in the middle stick?

**Comment by daudix-UFO** [comment]
> Merge the cube sides (it's a cube), make the middle stick in the 3 shorter, and I guess add a notch in the middle stick?

Что такое "notch in the middle stick" ?

**Comment by ArtyIF** [comment]
Ну как в 3 изгиб в середине

**Comment by daudix-UFO** [comment]
> 

Понял, сейчас сделаю

**Comment by daudix-UFO** [comment]
[📎 Warning.zip](https://github.com/ArtyIF/AdwCustomizer/files/9189500/Warning.zip)

**Comment by ArtyIF** [comment]
![image](https://user-images.githubusercontent.com/8017858/181022793-154946a5-c215-4856-95ed-d82065576914.png)

This is how it looks next to other icons. I think the objects need to be a bit more thick, if possible.

**Comment by daudix-UFO** [comment]
> ![image](https://user-images.githubusercontent.com/8017858/181022793-154946a5-c215-4856-95ed-d82065576914.png)
> 
> This is how it looks next to other icons. I think the objects need to be a bit more thick, if possible.

It will be a bit hard, because 3 is already nearly invisible, but will try

**Comment by daudix-UFO** [comment]
I have tried to make icon thicker and in same time readable, unsuccessfully, but I have made alternative versions, which is look pretty cool

> ![warning-red-mono](https://user-images.githubusercontent.com/77155297/181074147-63d48041-9003-4aaa-b137-25a49ea474ee.png)
> ![warning-red](https://user-images.githubusercontent.com/77155297/181074157-8d27a06c-24b3-4076-8dfc-547ed32e8e93.png)
> ![warning-orange-mono](https://user-images.githubusercontent.com/77155297/181074161-73e7bdee-ff6b-42d2-9942-55cfbe9766d9.png)
> ![warning-orange](https://user-images.githubusercontent.com/77155297/181074164-dc09e6e8-1384-4e65-bf94-6383a3ac23ee.png)
>

**Comment by daudix-UFO** [comment]
I tried to make icon thicker and in same time more readable, unsuccessfully, but I have a bit different version, and I think it will look good

![warning-red-mono](https://user-images.githubusercontent.com/77155297/181075500-a725252f-1b60-4139-bf75-53aecc1d0875.png)
![warning-red](https://user-images.githubusercontent.com/77155297/181075509-ab7d1c43-f0e4-46b9-805c-5158f16490a4.png)
![warning-orange-mono](https://user-images.githubusercontent.com/77155297/181075512-18f23f4b-97ce-4dba-8d4d-50fb653f972f.png)
![warning-orange](https://user-images.githubusercontent.com/77155297/181075518-c2b63ac5-152e-408a-b4df-d62a3a627d97.png)

[📎 SVG and Source](https://github.com/ArtyIF/AdwCustomizer/files/9192155/Warning-NEW.zip)

**Comment by ArtyIF** [comment]
Made some changes based on your icon. I think it looks good. Thank you for the base!
![image](https://user-images.githubusercontent.com/8017858/181100044-6997b29f-27ea-433f-84a7-3f2278d9e2ae.png)

TIL GTK renders objects without a fill and with a stroke as objects with a fill, and that you can change that by using Path -> Stroke to Path (Ctrl+Alt+C).

**Comment by daudix-UFO** [comment]
Спасибо сейчас совет! Выглядит очень хорошо.

**Comment by daudix-UFO** [comment]
И еще, совет от меня, контуры можно обеденять с помощью `Контур -> Сумма` так иногда легче работать.

**Comment by daudix-UFO** [comment]
Не по теме, но можно мне получить пресет темы "Pretty Purple - aka Purple Guy"?

**Comment by ArtyIF** [comment]
> Не по теме, но можно мне получить пресет темы "Pretty Purple"?

https://github.com/ArtyIF/AdwCustomizer/discussions/23

**Comment by daudix-UFO** [comment]
Большое спасибо!

**Comment by ArtyIF** [comment]
First option is good, but make the bottom right corner rounded as well, 
and the middle stick shorter a bit

**Comment by daudix-UFO** [comment]
Reopening?

**Comment by daudix-UFO** [comment]
@ArtyIF I'm a bit confused about this, is current icon bad?

**Comment by ArtyIF** [comment]
> @ArtyIF I'm a bit confused about this, is current icon bad?

IDK for some reason a bunch of email replies I wrote a while ago got processed just now. So ignore that

**Comment by daudix-UFO** [comment]
I know this situation 😄
