### ISSUE TITLE
feat: install adwcustomizer as python lib for being able to call base plugin

### ISSUE THREAD

**Issue by 0xMRTT** [GradienceTeam/Gradience#141]
### Feature description

Currently, Gradience is installed in `/usr/share/adwcustomizer/adwcustomizer`. Python can't load module from here, modules must be in `/usr/lib/python3.10/site-packages/`

I'm bad with meson, can someone help me ?

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/AdwCustomizerTeam/AdwCustomizer/blob/main/CODE_OF_CONDUCT.md).

**Comment by eli-schwartz** [comment]
https://github.com/AdwCustomizerTeam/AdwCustomizer/blob/88ec3317fcb282f5ea65e0c7343d5077fc9ca60a/src/meson.build#L64

Instead of install_data, you could use `python.find_installation('python3')`'s install_sources() method, which installs to the python site-packages.
