### ISSUE TITLE
bug: Not translatable items

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Some parts of app don't exist in .pot, this parts are:

- Tab switcher
- `Monet Palette` in `Monet` tab
- Whole `Plugins` section in `Advanced` tab
- `What's new` and `Details` sections in `About Gradience`

### To Reproduce

1. Open terminal
2. Run app with russian (or any other) locale: `flatpak run --env=LANG=ru com.github.GradienceTeam.Gradience.Devel`
3. Here is it

### Expected behavior

All strings being translatable

### Screenshots

![Report_1](https://user-images.githubusercontent.com/77155297/185680025-332dbe3e-7e9d-4c64-9ca0-cff4134adb52.png)
![Report_2](https://user-images.githubusercontent.com/77155297/185680033-2835fbae-4332-4fb8-88ca-6b97f778486a.png)
![Report_3](https://user-images.githubusercontent.com/77155297/185680035-328544e8-65e5-4531-8319-02645e6f81ae.png)
![Report_4](https://user-images.githubusercontent.com/77155297/185680038-4d850477-9bd5-48e0-a700-7ed4149098e6.png)
![Report_5](https://user-images.githubusercontent.com/77155297/185680039-6ed52694-b973-428a-9c22-502c99dfcd67.png)

### OS

Fedora Linux 36 (Silverblue edition)

### Version

0.1.0-2eea3e9

### Installation method

Flatpak from manual build - main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix-UFO** [comment]
Sorry for those dumb arrows

**Comment by 0xMRTT** [comment]
Fixed

**Comment by 0xMRTT** [comment]
Also, you can manually run the workflow for updating .pot (update every 6hours)

**Comment by daudix-UFO** [comment]
Thank you, next time will do it ;)

**Comment by 0xMRTT** [comment]
Just added this feature :D
