### ISSUE TITLE
feat: move all contributors to CONTRIBUTORS.md

### ISSUE THREAD

**Issue by 0xMRTT** [GradienceTeam/Gradience#214]
### Feature description

The idea of listing all contributors in README is amazing, but maybe it will be better to make a separate file and add link to it?
Because README slowly becomes unreadable

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible.

**Comment by 0xMRTT** [comment]
:crying_cat_face: 

Hi, I'm 0xMRTT. I want to contribute to Gradience, where should i start ?

**Comment by daudix-UFO** [comment]
Looks like @0xMRTT already have done it, closing?

**Comment by 0xMRTT** [comment]
Yes :+1:
