### ISSUE TITLE
feat: Support Monet with SVG wallpapers.

### ISSUE THREAD

**Issue by Adaoh2** [GradienceTeam/Gradience#217]
### Feature description

Add support for SVG wallpapers with the Monet engine, as GNOME uses SVG for (some) of its default wallpapers, like blobs.svg and blobs-d.svg. Right now, when selecting an SVG as an input file, nothing happens with the color palette.

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible.

**Comment by 0xMRTT** [comment]
`svg` [isn't supported](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html) by Pillow. So, i'm going to use [pillow_svg](https://github.com/gribbg/pillow_svg)

**Comment by 0xMRTT** [comment]
Done :white_check_mark:
