### ISSUE TITLE
feat: Add support for dconf to get the current wallpaper uri

### ISSUE THREAD

**Issue by Adaoh2** [GradienceTeam/Gradience#218]
### Feature description

Using dconf, it is possible to get the currently in use wallpaper. The dconf locations are: 
- `/org/gnome/desktop/background/picture-uri-dark` For dark wallpaper
- `/org/gnome/desktop/background/picture-uri` For light wallpaper

This would be very useful, as when using default wallpapers, it can be tricky navigating/finding the one currently in use. This would also be great in combination with #217 as it would enable for a better out of the box experience that would "just work".

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by 0xMRTT** [comment]
Done :white_check_mark:

**Comment by 0xMRTT** [comment]
@all-contributors please add @Adaoh2  for userTesting
