### ISSUE TITLE
bug: Flatpak install "org.gnome.Platform/x86_64/master" not found

### ISSUE THREAD

**Issue by jahinzee** [GradienceTeam/Gradience#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Flatpak install package does not install, it returns with the error:
```
error: The application com.github.AdwCustomizerTeam.AdwCustomizer/x86_64/master requires the runtime org.gnome.Platform/x86_64/master which was not found
```
Installing the latest version of `org.gnome.Platform/x86_64/` does not help, as there doesn't seem to be a `master` option.

Any help would greatly be appreciated.

### To Reproduce

1. Download the Flatpak file from Releases
2. Run `flatpak install com.github.AdwCustomizerTeam.AdwCustomizer.flatpak`

### Expected behavior

The Flatpak should install

### OS

Fedora Linux 36 (Workstation)

### Version

0.1.0

### Installation method

Flatpak from Github Actions - main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible.

**Comment by 0xMRTT** [comment]
Hi 👋 @jahinzee 

Recently, we changed the name from AdwCustomizer to Gradience.

So, in Flatpak, you need to run `flatpak install com.github.Gradience.GradienceTeam.flatpak`.

Tell me if you encounter any problems.

**Comment by 0xMRTT** [comment]
@all-contributors please add @jahinzee  for bug
