### ISSUE TITLE
feat: add OC to weblate

### ISSUE THREAD

**Issue by JeanGauthier** [GradienceTeam/Gradience#220]
### Feature description

Hello,
I would like to help translate into Occitan.
Could you add this language to weblate please?
Best regards

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible.

**Comment by 0xMRTT** [comment]
You are welcome 🙂

**Comment by 0xMRTT** [comment]
Added ✅

**Comment by JeanGauthier** [comment]
Many thanks

**Comment by 0xMRTT** [comment]
No problems. You are welcome 😎🚀
