### ISSUE TITLE
bug: dark theme doesn't apply

### ISSUE THREAD

**Issue by 0xMRTT** [GradienceTeam/Gradience#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We need to select dark and light for being able to use dark theme.

### Installation method

Manual using meson - main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aspizu** [comment]
GTK seems to ignore `gtk-dark.css`, moving `gtk-dark.css` to `gtk.css` in both the gtk-3.0 and gtk-4.0 dirs fixes it.

**Comment by 0xMRTT** [comment]
Yes, saw this. I've an idea for solving this problem. Will try to implement in next branch and for now, disabling the option to apply only for a color theme
