### ISSUE TITLE
Create a full theme preview

### ISSUE THREAD

**Issue by ArtyIF** [GradienceTeam/Gradience#24]
Something similar to GTK 4's Widget Factory, but with Libadwaita widgets thrown in there too.

**Comment by 0xMRTT** [comment]
@daudix-UFO Where should I had the button for opening this special window?

**Comment by daudix-UFO** [comment]
Hmm, will try to make it in mockup

**Comment by daudix-UFO** [comment]
Added, test button near to apply

**Comment by 0xMRTT** [comment]
![image](https://user-images.githubusercontent.com/105598867/185725342-f8dd4176-082b-4f17-b298-4e2b3d4a6e76.png)

:white_check_mark: Done
