### ISSUE TITLE
bug: new presets appear only after reopening preset manager

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

New presets appear only after reopening `Preset Manager`

### To Reproduce

1. Open `Preset Manager` (Palette icon)
2. Go to `Explore` tab and Install new preset
3. Go back to `Installed`, there is no new preset
4. Reopen `Preset Manager`, new preset now appears

### Expected behavior

Refresh list of installed plugins after installing new preset

### Screenshots

[Kooha-2022-08-25-03-07-25.webm](https://user-images.githubusercontent.com/77155297/186546212-fac72291-a64d-4ffa-b24b-4cc7805be082.webm)

### OS

Fedora Linux 36 (Silverblue edition)

### Version

0.1.0-e9dc56a

### Installation method

Flatpak from GitHub Actions - next

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Oh, @tfuxu missed to call reload preset 😎

**Comment by 0xMRTT** [comment]
Fixed
