### ISSUE TITLE
feat: undo button in toast after removing preset

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#261]
### Feature description

`Undo` button in toast after removing preset in `preset manager`

![Снимок экрана от 2022-08-25 03-10-50](https://user-images.githubusercontent.com/77155297/186546969-70215a73-b84f-4cd8-901c-8f452d745a3a.png)

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by 0xMRTT** [comment]
That's mean that we need to store the preset somewhere while waiting that the toast disappeared or maybe there is a signal sent when the toast disappear

**Comment by 0xMRTT** [comment]
https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/signal.Toast.dismissed.html

So, just connect to this signal and delete when it receives the signal
