### ISSUE TITLE
bug: theme preview not working

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

`Theme Preview` not working in latest Flatpak CI and local builds

### To Reproduce

1. Click on `Lab` icon
2. Click on all options

### Screenshots

[Kooha-2022-08-25-03-11-29.webm](https://user-images.githubusercontent.com/77155297/186546576-44034526-5028-439f-9f80-e62b9013ec2b.webm)

### OS

Fedora Linux 36 (Silverblue edition)

### Version

0.1.0-e9dc56a

### Installation method

Flatpak from GitHub Actions - next

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
It's because there arn't installed ?

**Comment by daudix-UFO** [comment]
They installed, but they are flatpaks and app seems to not see them

**Comment by 0xMRTT** [comment]
Oh yes, 😅. Totally forgot about Flatpak 😅😅😅

**Comment by daudix-UFO** [comment]
Everything works in Flathub version

**Comment by daudix-UFO** [comment]
Closing for now

**Comment by 0xMRTT** [comment]
Cool 😎
