### ISSUE TITLE
bug: monet engine not working

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#263]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

 `Monet engine` not working in latest Flatpak CI and local builds

### To Reproduce

1. Open `Monet` tab
2. Select background
3. Click `Apply`

### Screenshots

[Kooha-2022-08-25-03-11-53.webm](https://user-images.githubusercontent.com/77155297/186546714-4d6b9014-6697-4af6-9aae-aaa52ea015f5.webm)

### OS

Fedora Linux 36 (Silverblue edition)

### Version

0.1.0-e9dc56a

### Installation method

Flatpak from GitHub Actions - next

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
It can be slow... Strange, you don't have any traceback? 

Try running from command line using :

flatpak run uuid

**Comment by daudix-UFO** [comment]
<pre>

❯ flatpak run com.github.GradienceTeam.Gradience.Devel
DEBUG:root:disabled plugins: []

(process:2): Adwaita-WARNING **: 03:46:13.109: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
DEBUG:root:{}
DEBUG:root:file:///usr/share/backgrounds/gnome/adwaita-d.jpg
DEBUG:root:adwaita-d.jpg
DEBUG:root:/usr/share/backgrounds/gnome/adwaita-d.jpg
DEBUG:root:normal run
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/gradience/window.py", line 129, in on_monet_file_chooser_response
    self.monet_file_chooser_button.set_tooltip_text(
TypeError: Must be string, not GLocalFile
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/gradience/window.py", line 218, in on_apply_button
    if self.monet_image_file.endswith(".svg"):

</pre>

**Comment by 0xMRTT** [comment]
Thanks 👍. It's very helpful :D

Could you try with a PNG picture?

**Comment by daudix-UFO** [comment]
`❯ flatpak run com.github.GradienceTeam.Gradience.Devel`

<pre>

DEBUG:root:disabled plugins: []

(process:2): Adwaita-WARNING **: 03:51:42.022: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
DEBUG:root:{}
DEBUG:root:file:///usr/share/backgrounds/gnome/adwaita-d.jpg
DEBUG:root:adwaita-d.jpg
DEBUG:root:/usr/share/backgrounds/gnome/adwaita-d.jpg
DEBUG:root:normal run
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/gradience/window.py", line 129, in on_monet_file_chooser_response
    self.monet_file_chooser_button.set_tooltip_text(
TypeError: Must be string, not GLocalFile
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/gradience/window.py", line 218, in on_apply_button
    if self.monet_image_file.endswith(".svg"):

</pre>

**Comment by 0xMRTT** [comment]
Thanks 👍

It's a type error, don't know why you r getting this because on my setup everything is working well

**Comment by 0xMRTT** [comment]
Fixed :+1:
