### ISSUE TITLE
feature: add search in preset manager 

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Search not working in `Preset Manager`

### To Reproduce

1. Open `Preset Manager`
2. Open `Explore` tab
3. Search for `Pretty Purple`

### Screenshots

![Снимок экрана от 2022-08-25 03-10-35](https://user-images.githubusercontent.com/77155297/186546861-2ff042e9-b495-47b4-a1c2-fa1b2302fac5.png)

### OS

Fedora Linux 36 (Silverblue edition)

### Version

0.1.0-e9dc56a

### Installation method

Flatpak from GitHub Actions - next

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Yes, it's not implemented yet 😎😅

**Comment by 0xMRTT** [comment]
#368
