### ISSUE TITLE
feat: change height of select background button

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#265]
### Feature description

Make `Select Background` button be same height as `Apply` button

![Снимок экрана от 2022-08-25 03-11-15](https://user-images.githubusercontent.com/77155297/186547054-c64a0831-1ab5-4424-a40b-3ccd3629aeda.png)

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment]
This is last one

**Comment by 0xMRTT** [comment]
Or maybe the opposite? What's better?

**Comment by daudix-UFO** [comment]
`Apply` have the normal size, so it will look more polished

# Adwaita Demo

![image](https://user-images.githubusercontent.com/77155297/186550249-bfce60a0-1060-4321-af98-04fc4ba9c4c3.png)

# File Shredder (Raider)

![image](https://user-images.githubusercontent.com/77155297/186550018-ff06f873-172e-4906-9b34-f6c3b44ff3aa.png)

# Fragments

![image](https://user-images.githubusercontent.com/77155297/186550180-61b33a68-74b1-4c1f-a6d1-a689aa6feace.png)

**Comment by daudix-UFO** [comment]
And move the symbolic icon to the left

**Comment by 0xMRTT** [comment]
Thanks 👍

**Comment by 0xMRTT** [comment]
![image](https://user-images.githubusercontent.com/105598867/186631443-52978d85-1f2e-429d-bcfb-355c44f00b3a.png)
