### ISSUE TITLE
bug: preset manager not opening

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Clicking on `Palette` button don't opens the `Preset Manager`

`❯ flatpak run --env=LANG=en com.github.GradienceTeam.Gradience.Devel`

<pre>
(process:2): Gtk-WARNING **: 14:52:17.403: Locale not supported by C library.
	Using the fallback 'C' locale.
DEBUG:root:disabled plugins: []

(process:2): Adwaita-WARNING **: 14:52:17.850: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
DEBUG:root:{}
DEBUG:root:file:///usr/share/backgrounds/gnome/adwaita-l.jpg
DEBUG:root:adwaita-l.jpg
DEBUG:root:/usr/share/backgrounds/gnome/adwaita-l.jpg
DEBUG:root:normal run

(gradience:2): Gtk-CRITICAL **: 14:52:21.418: Unable to retrieve child object 'offline_label' from class template for type 'GradiencePresetWindow' while building a 'GradiencePresetWindow'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG:urllib3.connectionpool:https://raw.githubusercontent.com:443 "GET /GradienceTeam/Community/main/presets.json HTTP/1.1" 200 303
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/gradience/window.py", line 318, in on_presets_button_clicked
    GradiencePresetWindow().present()
  File "/app/lib/python3.10/site-packages/gradience/presets_manager_window.py", line 58, in __init__
    self.setup_explore()
  File "/app/lib/python3.10/site-packages/gradience/presets_manager_window.py", line 88, in setup_explore
    self.search_stack.set_visible("page_offline")
AttributeError: 'NoneType' object has no attribute 'set_visible'
</pre>

### To Reproduce

1. Click on `palette` button

### Expected behavior

A `Preset Manager` to show up

### Screenshots

[Kooha-2022-08-25-14-51-06.webm](https://user-images.githubusercontent.com/77155297/186658343-2027a714-c6c1-47f4-b5ac-474a15781fa3.webm)

### OS

Fedora Linux 36 (Silverblue edition)

### Version

0.1.0-22d7ac3

### Installation method

Flatpak from manual build - next

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Could you retry ?

**Comment by daudix-UFO** [comment]
Now it's working!
