### ISSUE TITLE
feat: Automatically add support for Flatpak overrides

### ISSUE THREAD

**Issue by ItsJamie9494** [GradienceTeam/Gradience#276]
### Feature description

Currently, in order to add an override, you have to manually use Flatseal, or run `sudo`. This, in my opinion, is a bad UX. There's a way to automatically add overrides to Flatpak by modifying a few files.

## Adding Overrides to the User

The file located in `~/.local/share/flatpak/overrides/global` is how Flatpak reads it's overrides.
If this file is blank or non-existent, it can be replaced by a file containing two lines:

```toml
[Context]
filesystems=xdg-config/gtk-3.0;xdg-config/gtk-4.0;
```

If the file exists with data, appending either the existing `filesystems` line (a semicolon-delimited list) or adding it will achieve the same effect

## Adding Overrides to the Global

The procedure is the same as above, except the file is located at `/var/lib/flatpak/overrides/global`. This, of course, requires root permissions and changes settings for all users, and probably should not be used as much.

## Proposal

During first start, Gradience could ask the user if they would like to automatically enable Flatpak support, adding these lines. Of course, Gradience should also have some way to remove these lines and "disable" Flatpak support.

### Additional Context

If you're interested, Flatseal itself does this by checking the values of some environment variables. If these variables do not exist, Flatseal uses the paths I explained above.

You may view these functions at https://github.com/tchx84/Flatseal/blob/master/src/models/applications.js#L34-L60

Another important thing is that the format of the `global` file is a GLib KeyFile (https://docs.gtk.org/glib/struct.KeyFile.html, https://lazka.github.io/pgi-docs/#GLib-2.0/classes/KeyFile.html), and instead of parsing this file manually, you can use KeyFile functions instead. For example, GLib.KeyFile.get_string_list would return a List of all the values, instead of parsing manually and splitting the file. This is what Flatpak does in their source code

```c
g_key_file_get_string_list (metakey, FLATPAK_METADATA_GROUP_CONTEXT,
                            FLATPAK_METADATA_KEY_FILESYSTEMS, NULL, error);
```

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible.

**Comment by 0xMRTT** [comment]
Fixed 👍
