### ISSUE TITLE
bug: Flatpak link in readme does not work

### ISSUE THREAD

**Issue by DivineBicycle** [GradienceTeam/Gradience#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When clicking the link in the readme to open Flathub, Flathub gives an app not found error. When searching Flathub for Gradience no results are found

### To Reproduce

1. Open the readme
2. Click ```Download on Flathub```

### Expected behavior

I expected to see it on Flathub

### App not found error
![image](https://user-images.githubusercontent.com/78889625/187346390-70651695-8b4e-400b-a64f-6f19cfbd1356.png)

### Gradience not found when searching for it
![image](https://user-images.githubusercontent.com/78889625/187346419-1703e92e-4974-4635-bc15-7f25b7092d03.png)
![image](https://user-images.githubusercontent.com/78889625/187346548-34f4bd37-e796-4f74-a3f0-b11e7d51ec79.png)

### OS

Arch Linux

### Installation method

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LyesSaadi** [comment]
~~Blame @daudix-UFO.~~ (just kidding)

It's coming soon, you can already install Gradience using `flatpak install Gradience` or find it in `gnome-software`. It's just that Flathub's website isn't updated yet.

**Comment by DivineBicycle** [comment]
Does that pull request fix the issue for now?

**Comment by LyesSaadi** [comment]
Well, that will be solved by itself in a matter of hours, as soon as flathub.org updates. Although, I agree this isn't ideal :sweat_smile:, let's just avoid unnecessarily double reversion for something temporary. Let's just keep this issue along until it is solved if someone else gets this problem and gets confused.

**Comment by daudix-UFO** [comment]
I will hide the badge for now, sorry for this 😅

**Comment by daudix-UFO** [comment]
fixed in https://github.com/GradienceTeam/Gradience/commit/c83ee40d4e8ffc165fbd8d62f66e3136d87f983d

**Comment by LyesSaadi** [comment]
It works now, sent a push request to add it back.

**Comment by daudix-UFO** [comment]
Thanks for reminding
