### ISSUE TITLE
feat: change screenshots 

### ISSUE THREAD

**Issue by 0xMRTT** [GradienceTeam/Gradience#290]
### Feature description

Screenshots are old, one is for the first version of Gradience, I think that it would be great to have a screenshot of the preset manager and of monet

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment]
There are all needed screenshots in design repo, one screenshot is old, and it's the work proof, will make it soon 😉
