### ISSUE TITLE
bug: several missing translatable strings

### ISSUE THREAD

**Issue by libreajans** [GradienceTeam/Gradience#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, I was completed Turkish translation before new release and it's fully translated (100%). When I installed Gradience I saw it has several missing translations.

Eg, welcome dialog wasn't translated.

### To Reproduce

Install Gradience with Turkish locale and start it.

### OS

Ubuntu 22.04.1

### Version

0.2.1

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible. You can also join the matrix room.

**Comment by 0xMRTT** [comment]
Which install method ?

Also could you check in the po sir if the file for Turkish translation is full.

If not, i will push translations from weblate.

**Comment by 0xMRTT** [comment]
Oh, i know.

It's because Gradience.pot hasn't been update

**Comment by 0xMRTT** [comment]
Fixed in #307
