### ISSUE TITLE
bug: Constantly crashes

### ISSUE THREAD

**Issue by admin-ribbon** [GradienceTeam/Gradience#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This app will freeze and crash after a few minutes of running. It happens all the time

### To Reproduce

1. Launch Gradience
2. Let the apps running for a few moment
3. *freezes*

### Expected behavior

The app should runs fine and stable

### OS

Ultramarine Linux (Fedora 36)

### Version

0.2.0

### Installation method

Flatpak from Flathub

### Additional context

Fresh installed from GNOME Software

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible. You can also join the matrix room.

**Comment by daudix-UFO** [comment]
Can you please provide a logs and maybe screen recording?

Run Gradience from Terminal with this:

`flatpak run com.github.GradienceTeam.Gradience`

And comment output, make it using 3 (```) in start and end of log

**Comment by admin-ribbon** [comment]
This is very weird

I cannot replicate the bug for some reason
The program runs... well now?

I swear to god that the program doesn't work that well before this
And FYI, I haven't restarted my system yet after installing this app
I... can't tell...

But the Terminal did show an error message tho

```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gradience/main.py", line 559, in apply_color_scheme
    with open(
OSError: [Errno 30] Read-only file system: '/home/user/.var/app/com.github.GradienceTeam.Gradience/config/gtk-4.0/gtk.css'
```

This error appear when I tried to apply a theme (which by itself doesn't do anything)

**Comment by 0xMRTT** [comment]
Oh, you missed to setup Flatpak. Read the README, the setup will be automated in the next version.

**Comment by 0xMRTT** [comment]
https://github.com/GradienceTeam/Gradience#setup-tutorial
