### ISSUE TITLE
feat: Gruvbox theme

### ISSUE THREAD

**Issue by vanillajonathan** [GradienceTeam/Gradience#317]
### Feature description

I would like a theme with the Gruvbox palette.

https://github.com/morhetz/gruvbox-contrib#palette

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible. You can also join the matrix room.

**Comment by 0xMRTT** [comment]
It should be in Community

**Comment by vanillajonathan** [comment]
Alright. https://github.com/GradienceTeam/Community/issues/8
