### ISSUE TITLE
feat: compactness

### ISSUE THREAD

**Issue by clumsyfingers** [GradienceTeam/Gradience#324]
### Feature description

does this support editing the compactness of adwaita? its WAY too fat for me, its like playing with duplo when you want lego

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible. You can also join the matrix room.

**Comment by 0xMRTT** [comment]
You can use custom CSS and when plugin will be , you will be able to create a plugin for

**Comment by daudix-UFO** [comment]
This is not an app issue but a CSS request, I close this issue

**Comment by firefoxlover** [comment]
[this might help](https://github.com/archbyte/Adwaita-Slim/blob/dark/gtk-contained.css) but I didnt get any results and it is only for GTK3
