### ISSUE TITLE
Restore to default Adwaita

### ISSUE THREAD

**Issue by alex285** [GradienceTeam/Gradience#330]
### Feature description

apologies if I'm missing something, but how we are supposed to revert back to the default experience? for example if we select Adwaita Light/Dark from presets, GNOME Scheme Switch wont work anymore;

even if there this functionality somewhere, can you make it a bit more obvious? like "Go back to default GNOME!" 

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible. You can also join the matrix room.

**Comment by LyesSaadi** [comment]
![image](https://user-images.githubusercontent.com/33597258/188287093-37413703-ba8a-401f-9b19-c91c5a72668c.png)

**Comment by LyesSaadi** [comment]
Oh, forgot translations. Anyway, that second button :P !

**Comment by alex285** [comment]
tried those already, but they didn't work; will investigate a bit more tomorrow and open a bug! thanks!

however i still think this is not clear enough; it looks more like "reset" the current theme you're editing;

**Comment by LyesSaadi** [comment]
Did you close the apps and reopen them ?

**Comment by alex285** [comment]
I even restarted Shell (logged in/out); but i didnt try to manually revert  ..and somehow now it (theme switching) worked, maybe was on some Shell bug :/ 

so im closing this i guess
