### ISSUE TITLE
bug: Missing or wrong strings in pot file

### ISSUE THREAD

**Issue by libreajans** [GradienceTeam/Gradience#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, 

There are several missing or wrong strings in pot file that affect user experience.

| Real String  | On Pot File | Source | 
| ------------- | ------------- | ------------- |
| Configure Themes  | Configure themes  | welcome.blp |
| System Configuration  | System configuration  | welcome.blp |
| Installing Themes | Installing themes | welcome.blp |
| Please wait until themes will be installed. | pot file have whitespace at the end of string | welcome.blp |
| Restore applied color scheme? | Missing in pot file | main.py | 
| Preferences | Missing in pot file | preferences.blp | 
| Flatpak Specific | Missing in pot file | preferences.blp | 
| Allow Flatpak theming | Missing in pot file | preferences.blp | 
| Allow Flatpak theming (Global) | Missing in pot file | preferences.blp | 
| Override Flatpak permissions for current user to allow Flatpak applications to access custom themes. | Missing in pot file | preferences.blp | 
| Override Flatpak permissions for all users to allow Flatpak applications to access custom themes. (Requires root access) | Missing in pot file | preferences.blp | 

### To Reproduce

-

### Expected behavior

They should be translated or translatable.

### OS

Ubuntu 22.04.1

### Version

0.2.2

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
The pot file is automatically generated every 6 hours and can be manually triggered. Thanks to @AdwCustomizer, it's automatically fixed. 

If you see this issue again, we just need to manually trigger the workflow or wait (generation 2 times per day)
