### ISSUE TITLE
bug: theme changes not applied to flatpak apps

### ISSUE THREAD

**Issue by abelptvts** [GradienceTeam/Gradience#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

First of all, thank you for this great initiative! 

Theme changes are not being applied in the case of flatpak apps. Neither for libadwaita, not for gtk based ones. 

I'm using the flapak installation of Gradience (which doesn't remember the theme choice either). Tested with the flatpak installation of Deja Dup Backups and Gnome Markets. 

I'm confident that I've done my setup properly: adw-gtk theme installed in flatpak as well, added the overrides, did the setup for vanilla gtk-4.

### To Reproduce

- Install Gradience using flatpak
- Perform all the required setup steps
- Select the classic-dark color scheme
- Install Deja Dup Backups as a flatpak app

### Expected behavior

Deja Dup Backups should respect the theme applied using Gradience. 

### Screenshots

![Screenshot from 2022-09-04 11-39-04](https://user-images.githubusercontent.com/42967624/188307292-a48c6d98-2792-462e-90b0-c024a6d2b95c.png)

The left side shows Pop!_Shop abiding to the theme choice, and Deja Dup on the right side looking like it's using the default adwaita theme.

### OS

Pop-OS 22.04 LTS

### Version

0.2.1

### Installation method

Flatpak from Flathub

### Additional context

Let me know if you need additional information.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible. You can also join the matrix room.

**Comment by 0xMRTT** [comment]
Oh, yes it's an error on Gradience's side

It's only applied for gtk3 but not for gtk4

**Comment by 0xMRTT** [comment]
Could you try to open Gnome Text Editor ?

Because it's working with gnome text editor (GTK4 + libadwaita but not with GNOME Software)

**Comment by abelptvts** [comment]
Same issue with the flatpak installation of Gnome Text Editor.

**Comment by 0xMRTT** [comment]
Not fore me :/

**Comment by 0xMRTT** [comment]
Will try to fix that :rocket:

**Comment by 0xMRTT** [comment]
Could you check if there is `.config/gtk-4.0/gtk.css` and same for gtk3 ?

**Comment by abelptvts** [comment]
Yep, the files exist. 

```
$ ls .config/gtk-*
.config/gtk-2.0:
gtkfilechooser.ini

.config/gtk-3.0:
bookmarks  gtk.css  gtk.css.bak  servers  settings.ini

.config/gtk-4.0:
gtk.css  gtk.css.bak  settings.ini
```

**Comment by abelptvts** [comment]
I also have adw-gtk3 installed as flatpak (alongside the normal installation).

```
$ flatpak list | grep adw
adw-gtk3 Gtk Theme	org.gtk.Gtk3theme.adw-gtk3		3.22	user
adw-gtk3-dark Gtk Theme	org.gtk.Gtk3theme.adw-gtk3-dark		3.22	user
```

**Comment by abelptvts** [comment]
Also, it seems like my flatpak apps are using the adw-gtk3 flatpak themes successfully. It feels like the issue is around the overrides that apply to the flatpak theme.

**Comment by 0xMRTT** [comment]
Could you check the content of gtk-4.0 ?

**Comment by abelptvts** [comment]
The contents of the directory are the following:
```
$ ls -l
total 12
-rw-r--r-- 1 abelptvts abelptvts 2807 Sep  4 11:07 gtk.css
-rw-r--r-- 1 abelptvts abelptvts 2807 Sep  4 11:07 gtk.css.bak
-rw-rw-r-- 1 abelptvts abelptvts   47 Sep  2 10:41 settings.ini
```

The contents of gtk-4.0/gtk.css are:

```
@define-color accent_color #4f6989;
@define-color accent_bg_color #3584e4;
@define-color accent_fg_color rgb(255,255,255);
@define-color destructive_color #ff7b63;
@define-color destructive_bg_color #c01c28;
@define-color destructive_fg_color rgb(255,255,255);
@define-color success_color #8ff0a4;
@define-color success_bg_color #26a269;
@define-color success_fg_color rgb(255,255,255);
@define-color warning_color #f8e45c;
@define-color warning_bg_color #cd9309;
@define-color warning_fg_color rgba(0, 0, 0, 0.8);
@define-color error_color #ff7b63;
@define-color error_bg_color #c01c28;
@define-color error_fg_color rgb(255,255,255);
@define-color window_bg_color #101010;
@define-color window_fg_color #e0e0e0;
@define-color view_bg_color #101010;
@define-color view_fg_color rgb(224,224,224);
@define-color headerbar_bg_color #222222;
@define-color headerbar_fg_color #e0e0e0;
@define-color headerbar_border_color #ffffff;
@define-color headerbar_backdrop_color @window_bg_color;
@define-color headerbar_shade_color rgba(0, 0, 0, 0.36);
@define-color card_bg_color #232323;
@define-color card_fg_color #e0e0e0;
@define-color card_shade_color rgba(0, 0, 0, 0.36);
@define-color dialog_bg_color #101010;
@define-color dialog_fg_color #ffffff;
@define-color popover_bg_color #212121;
@define-color popover_fg_color #e0e0e0;
@define-color shade_color #383838;
@define-color scrollbar_outline_color rgba(0, 0, 0, 0.5);
@define-color blue_1 #99c1f1;
@define-color blue_2 #62a0ea;
@define-color blue_3 #3584e4;
@define-color blue_4 #1c71d8;
@define-color blue_5 #1a5fb4;
@define-color green_1 #8ff0a4;
@define-color green_2 #57e389;
@define-color green_3 #33d17a;
@define-color green_4 #2ec27e;
@define-color green_5 #26a269;
@define-color yellow_1 #f9f06b;
@define-color yellow_2 #f8e45c;
@define-color yellow_3 #f6d32d;
@define-color yellow_4 #f5c211;
@define-color yellow_5 #e5a50a;
@define-color orange_1 #ffbe6f;
@define-color orange_2 #ffa348;
@define-color orange_3 #ff7800;
@define-color orange_4 #e66100;
@define-color orange_5 #c64600;
@define-color red_1 #f66151;
@define-color red_2 #ed333b;
@define-color red_3 #e01b24;
@define-color red_4 #c01c28;
@define-color red_5 #a51d2d;
@define-color purple_1 #dc8add;
@define-color purple_2 #c061cb;
@define-color purple_3 #9141ac;
@define-color purple_4 #813d9c;
@define-color purple_5 #613583;
@define-color brown_1 #cdab8f;
@define-color brown_2 #b5835a;
@define-color brown_3 #986a44;
@define-color brown_4 #865e3c;
@define-color brown_5 #63452c;
@define-color light_1 #ffffff;
@define-color light_2 #f6f5f4;
@define-color light_3 #deddda;
@define-color light_4 #c0bfbc;
@define-color light_5 #9a9996;
@define-color dark_1 #77767b;
@define-color dark_2 #5e5c64;
@define-color dark_3 #3d3846;
@define-color dark_4 #241f31;
@define-color dark_5 #000000;
```

**Comment by 0xMRTT** [comment]
Try to kill app using system monitor and re apply or try to log out login and re apply

**Comment by abelptvts** [comment]
Everything's the same unfortunately.

**Comment by 0xMRTT** [comment]
😿

**Comment by 0xMRTT** [comment]
I don't use flatpak but @daudix-UFO do and he doesn't have any problems

**Comment by abelptvts** [comment]
Closing, I managed to fix it. Weirdly enough, all I needed to do was to specify the flatpak overrides using Flatseal instead of the flatpak CLI. I suspect it's due to the fact that XDG_CONFIG_HOME is undefined by default on my system... Anyway, thank you for the support!

**Comment by 0xMRTT** [comment]
Thanks you for using Gradience :+1:

**Comment by 0xMRTT** [comment]
Also, you can join the matrix room or the discord server for more.
