### ISSUE TITLE
bug: Toasts block the app thread

### ISSUE THREAD

**Issue by vieruuuu** [GradienceTeam/Gradience#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Trying to delete/apply multiple presets but the toasts/bottom notifications block the main thread i suppose.

### Expected behavior

Toasts should not block the app from deleting presets, applying, etc.

### OS

Arch Linux

### Installation method

AUR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible. You can also join the matrix room.

**Comment by 0xMRTT** [comment]
Fixed :+1: 

Thanks
