### ISSUE TITLE
bug: Unable to start on fedora

### ISSUE THREAD

**Issue by nlogozzo** [GradienceTeam/Gradience#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The application fails to start.
Error from console:
```
Traceback (most recent call last):
  File "/usr/bin/gradience", line 64, in <module>
    from gradience import main
  File "/usr/lib/python3.10/site-packages/gradience/main.py", line 29, in <module>
    from .window import GradienceMainWindow
  File "/usr/lib/python3.10/site-packages/gradience/window.py", line 32, in <module>
    from .app_type_dialog import GradienceAppTypeDialog
  File "/usr/lib/python3.10/site-packages/gradience/app_type_dialog.py", line 25, in <module>
    class GradienceAppTypeDialog(Adw.MessageDialog):
  File "/usr/lib64/python3.10/site-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'MessageDialog'
```

### To Reproduce

1. Install on fedora 36 using the following: `sudo dnf copr enable lyessaadi/gradience` and `sudo dnf install gradience`
2. Launch application

### Expected behavior

The application launchs and runs without error

### OS

Fedora Linux 36 (Workstation)

### Version

0.2.2

### Installation method

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible. You can also join the matrix room https://matrix.to/#/#Gradience:matrix.org or the discord server https://discord.com/invite/rwNDGPJf

**Comment by tfuxu** [comment]
Are you able to open about window?

**Comment by Corrupter-rot** [comment]
Just installed it earlier this day, got the same issue. Tried to compile it from the source. The Error I got was from `libawiata 1.1` not found.

**Comment by nlogozzo** [comment]
> Just installed it earlier this day, got the same issue. Tried to compile it from the source. The Error I got was `libawiata 1.1` not found when compiling. ( Command was `sudo meson builddir --prefix=/usr/local` )

Well I have libadwaita 1.1 installed. Could it be that it requires 1.2?

**Comment by tfuxu** [comment]
Yes, it requires libadwaita >= 1.2.alpha

**Comment by tfuxu** [comment]
Looks like Fedora 36 is stuck on version 1.1.0-1

**Comment by tfuxu** [comment]
Hmm, @LyesSaadi provides version 1.2.beta for Fedora 36 in his copr, maybe you should be able to update libadwaita from that?

**Comment by LyesSaadi** [comment]
Hello, you need to do :
```
sudo dnf upgrade
```

**Comment by LyesSaadi** [comment]
Oh, the fact that it didn't update automatically was an error, my bad, will solve that!

**Comment by nlogozzo** [comment]
Oh ok I will check out the copr and update libadwaita...thanks!

**Comment by nlogozzo** [comment]
@LyesSaadi just a heads up...libadwaita 1.2.0 official was released a few days ago you might want to look into updating the copr with that new version

**Comment by LyesSaadi** [comment]
> @LyesSaadi just a heads up...libadwaita 1.2.0 official was released a few days ago you might want to look into updating the copr with that new version

Yup, thanks for the reminder!

**Comment by Corrupter-rot** [comment]
Last thing after updating everything worked fine but there was an error for a python module `pluggy` which was not installed automatically.

```
>>  gradience 
Traceback (most recent call last):
  File "/usr/bin/gradience", line 64, in <module>
    from gradience import main
  File "/usr/lib/python3.10/site-packages/gradience/main.py", line 29, in <module>
    from .window import GradienceMainWindow
  File "/usr/lib/python3.10/site-packages/gradience/window.py", line 35, in <module>
    from .plugins_list import GradiencePluginsList
  File "/usr/lib/python3.10/site-packages/gradience/plugins_list.py", line 25, in <module>
    import pluggy
ModuleNotFoundError: No module named 'pluggy'
```

The error was solved by installing the package through pip. Just letting you know this.

**Comment by 0xMRTT** [comment]
@LyesSaadi, we need to update the spec with pluggy because i'll use that for the plugin system

**Comment by LyesSaadi** [comment]
> @LyesSaadi, we need to update the spec with pluggy because i'll use that for the plugin system

Uh, when was it added? In 0.2.2 or still is in master?

**Comment by 0xMRTT** [comment]
Don't know 😅

**Comment by LyesSaadi** [comment]
It was... :/... At least it is in Fedora.

Anyway, I think I'm writing release notes instructions. The issue is that pluggy was not installed in the flatpak either :/...
