### ISSUE TITLE
feat: refactor logic of nightly builds

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#369]
### Feature description

Now `.Devel` flatpaks are not generating because we don't use `next` branch any more, so we need to change the logic of CI and local builds

as example here is typical GNOME Circle app build logic:

- You can build regular or `.Devel` version using GNOME Builder
- Building from source builds `.Devel` Flatpak
- Nightly builds don't have locales
- Stable releases available on Flathub

I suggest following changes:

- Building from source will build `.Devel`
- CI will build `.Devel` version only (without locales)
- Stable version are builds using flatpak-builder when we push new release

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by 0xMRTT** [comment]
My proposal:

- A job for building devel on push or pr
- instructions in the README for manual build
- instructions in the release process forbuilding stable release

**Comment by daudix-UFO** [comment]
+

**Comment by 0xMRTT** [comment]
I modified the GitHub actions

**Comment by 0xMRTT** [comment]
I think that's done ✅

**Comment by daudix-UFO** [comment]
Good 👍

**Comment by 0xMRTT** [comment]
Also, idk if you saw but the aarch64 build was a success. You can now try Gradience on mobile 😎

**Comment by daudix-UFO** [comment]
If only I had one :D (I mean Pinephone or Librem)
