### ISSUE TITLE
bug: local builds doesn't work

### ISSUE THREAD

**Issue by tfuxu** [GradienceTeam/Gradience#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This is a pretty old bug, as local builds doesn't work since we changed installation location to `PY_INSTALLDIR`.
As on how to resolve this, we have two options:
- Switch back to `MODULE_DIR`,
- Slightly change the installation procedure

We can base a second option on what is in [GNOME Music](https://gitlab.gnome.org/GNOME/gnome-music#build-music) or [Apostrophe](https://gitlab.gnome.org/World/apostrophe#building).

### Screenshots

![Zrzut ekranu z 2022-09-10 14-07-36](https://user-images.githubusercontent.com/73042332/189482650-d7cb0a46-9e8e-4caa-8efc-e3a9fc9fe3f0.png)

### Version

0.2.2-main

### Installation method

Manual using meson - main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
I know. It's because of your old locales build. 

In fact:

You build and when you re build you don't delete old build but just overwriting some files.

I've got this error and when I reinstalled my computer the error disappeared maybe try to remove all local installed files related to gradience

**Comment by tfuxu** [comment]
> I know. It's because of your old locales build.
> 
> In fact:
> 
> You build and when you re build you don't delete old build but just overwriting some files.
> 
> I've got this error and when I reinstalled my computer the error disappeared maybe try to remove all local installed files related to gradience

Really? I'll check that, fortunately I'm doing this on VM so it should be only a snapshot revert for me.

**Comment by 0xMRTT** [comment]
You develop in a VM ?

**Comment by tfuxu** [comment]
No, I'm just testing Gradience in a VM

**Comment by 0xMRTT** [comment]
Compatibility should be fixed now

**Comment by tfuxu** [comment]
Updated screenshot to show exactly a reported bug

**Comment by tfuxu** [comment]
Updated screenshot to show exactly a reported bug

**Comment by 0xMRTT** [comment]
We must keep installation in `PY_INSTALLDIR` because of plugins.

**Comment by tfuxu** [comment]
Ok, we have some progress. I've got it to work, and it shouldn't even require modifying any of a installation instructions.
Here are the screenshots:
![Zrzut ekranu z 2022-09-12 21-27-06](https://user-images.githubusercontent.com/73042332/189739683-28a9dad4-636a-4956-857f-18a269ce2cb8.png)

![Zrzut ekranu z 2022-09-12 21-30-34](https://user-images.githubusercontent.com/73042332/189739700-9d026405-00bb-414b-9f3b-1029086cad58.png)
Unfortunately Gradience still has the same problem with icons as before, but for testing purposes, I think it isn't that big of a deal. 
The exciting part is that translations are now fully working on local builds.

**Comment by 0xMRTT** [comment]
Cool, what did you do ?

**Comment by tfuxu** [comment]
I modified meson structure a little bit, and renamed `src` directory to `gradience` so it can properly import modules. I'll create a PR for this, so don't close this issue for now.

**Comment by 0xMRTT** [comment]
Okay 👌.

**Comment by tfuxu** [comment]
Fixed in pull request #400
