### ISSUE TITLE
bug: Renaming a preset causes it to be overwritten entirely

### ISSUE THREAD

**Issue by EntityinArray** [GradienceTeam/Gradience#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Renaming a preset (giving a different name is not necessary, just clicking the pencil icon button 2 times is enough) causes the preset to be overwritten entirely with current colors.

### To Reproduce

1. Open Gradience
2. Go to Palettes window
3. Find a random palette (make sure it's not necessary to you or that it has been backed up) and click the pencil icon 2 times.
4. Gradience will show 'Preset renamed' toast
5. Notice how it's now overwritten by Adwaita Dark

### Expected behavior

Gradience should only rename the preset, not perform an entire overwriting save.

### OS

Nobara Linux 36 (based on Fedora)

### Version

0.2.2

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Currently when you rename a preset, gradience change the name in a file, and rename the filename. It's not the current behaviour?

**Comment by EntityinArray** [comment]
Hi! I recently did flatpak update and it overwrites the entire pallette on renames for me. I recorded a video that demonstrates the issue.
[overwrite_bug.webm](https://user-images.githubusercontent.com/18554021/189475050-002b927c-75e3-4270-b950-1cfc3279be93.webm)

**Comment by 0xMRTT** [comment]
Oh, I see :+1: 

Thanks for reporting this issue, i'm fixing RN

**Comment by EntityinArray** [comment]
Thank you for such quick response and working on this amazing project. I really appreciate it!

**Comment by 0xMRTT** [comment]
Fixed, thanks for reporting this issue
