### ISSUE TITLE
bug: Themes not applying at all

### ISSUE THREAD

**Issue by roracle** [GradienceTeam/Gradience#395]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

After applying a theme, nothing actually sticks.  I've tried to make changes via flatseal but nothing seems to work.

### To Reproduce

1.Open Gradience 
2. Apply theme (any of the downloadable is fine) to GTK 3 and 4
3. Check demos. Adwita demo is correct, GTK is not.
4. Close and reopen, notice theme is reset.

### Expected behavior

Expected to apply the theme user-wide.

### OS

Fedora 36

### Version

0.2.2

### Installation method

Flatpak from Flathub

### Additional context

Another bug report is coming for the RPM version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdwCustomizer** [comment]
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible. You can also join the matrix room https://matrix.to/#/#Gradience:matrix.org or the discord server https://discord.com/invite/rwNDGPJf

**Comment by 0xMRTT** [comment]
Oh, yes. It's a know issue, I'll remove the GTK4 Demo and autoload the current theme

**Comment by 0xMRTT** [comment]
See #396

**Comment by 0xMRTT** [comment]
I've added the autoload of css
