### ISSUE TITLE
feat: release 0.3

### ISSUE THREAD

**Issue by 0xMRTT** [GradienceTeam/Gradience#397]
# Release 0.3.0

<details>

<summary> Checklist</summary>

### A week before release
- [x] Announce the upcoming release by creating a new issue one week before the release.
- [x] Ask translators to translate new strings.
- [x] In the issue, prepare release notes :
  - [x] The first section would be a summary of big changes.
  - [x] The second section should list new dependencies, including python dependencies, and the reason they were added.
  - [x] The third section would be the list of contributions.

### 3 days before release
- [x] Sign off on the release notes (or at least the first section).
- [x] Update the meson version number.
- [x] Add the release notes' first section's content to the AppData.
- [ ] Create a new branch for the release with the name being the release number and freeze new feature, only merge in bug fixes and translation updates.
- [x] Create a flathub test build (by creating a pull request in the flathub repo, bumping the release tag in it, and asking Flathub's buildbot to build it).
- [x] Ask contributors to test the build. Any identified bug should halt the update until fixed.

## Doing the release
- [ ] Tag the lastest commit in the release branch with the version number.
- [ ] Create a new GitHub release using the approved release notes.

## After the release
- [ ] Upgrade the flathub package by bumping the release tag.
- [ ] Notify packagers.
- [x] Write a TWIG announcement.

</details>

### App

- Added back the quick preset switcher
- Autoload theme from applied css
- Added plugins support
- Show save dialog if user want to close with unsaved changes

### Plugins

- First plugin for customizing GNOME Firefox Theme

### Preset manager

- Added custom repos
- Added dropdown repo selctor to the search
- Added repo badge (report if colours are bad)
- Added Adw.ExpanderRow for installed presets
- Added Description in installed presets
- Added dropdown menu for reporting bug about preset
- Download and fetch is now asynchronous

## Dependencies

- `python-cssutils`
- `python-yapsy`
- `python-aiohttp`
- `python-jinja2`
- `python-svglib`
- `python-material-color-utilities-python`
- `python-anyascii`
- `python-gobject`
- `blueprint-compiler`
- `gtk4`
- `libadwaita >= 1.2`
- `meson`
- `ninja-build`
- `python`
- `sassc`

## Contributors

As always, biggest contributors are members of the @GradienceTeam:
- @0xMRTT 
- @daudix-UFO 
- @tfuxu 
- @LyesSaadi 

### Translators

Thanks to all translators who did an amazing work on Weblate or Crowdin (if your name isn't here, ping me on Matrix or here)

- Korean: @vbalien
- Portugese: @renatocrrs
- English US: @BritishBenji 
- French: @rene-coty
- Tamil: @kbdharun 
- Swedish: @bittin
- Italian: @phaerrax
- Dutch: @emansom
- German: @rene-coty

**Comment by 0xMRTT** [comment]
As we said, before the release we must check everything :rocket: 

In this release there will be a lot of changes:
- plugins
- repo
- community refactor
- transform css into preset
- maybe i missed something :1st_place_medal:  ??

**Comment by daudix-UFO** [comment]
I want to create another ui polish request, so if you are not against we can release after it ;)

**Comment by 0xMRTT** [comment]
I'm not against :+1:. I'm so glad, i've added maybe the most requested feature ...

**Comment by daudix-UFO** [comment]
I think we can release it before TWIG 😎🔥

**Comment by LyesSaadi** [comment]
Will be able to take enough time to make sure everything works :3 !

**Comment by daudix-UFO** [comment]
#406

**Comment by daudix-UFO** [comment]
What about #12 ?

**Comment by daudix-UFO** [comment]
Small but important, there is no icon in app launcher for developed version, and launching from CLI only is not best option 😄

**Comment by LyesSaadi** [comment]
0.3.1 IS OUT ! WOOOOOOOHOOOOOOOO !
