### ISSUE TITLE
feat: yet another UI/UX polish

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#406]
### UI improvements that would be nice to see

- [x] Add quick preset switcher back, it was pretty useful
- [x] Warning dialog when closing Gradience and preset are not saved
- [x] Don't show "Preset renamed" toast in preset manager
- [x] Repo indicator, e.g `Official` and `Curated`, useful when preset have official and unofficial variant
- [x] Warning dialog when resetting applied preset
- [x] Hide preset immediately after pressing `remove` and not after closing toast
- [x] Show only presets from selected repo using repo switcher
- [x] Add paddings to explanation box
- [x] Display only starred presets in Quick Preset Switcher
- [x] Add categories in about window for other contributors like plugin devs using https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/method.AboutWindow.add_credit_section.html
- [x] Fix really odd `no_plugin_pref`
- [x] Change the presets repo indicators
- [x] Fix `.Devel` version don't have launch icon
- [x] Place "Preferences" button to the right from the switch in plugins tab
- [x] #629
- [ ] Make the "Tone" settings in Monet tab work
- [ ] Improve color description text (popup on clicking light bulb)
- [ ] Refactor "Colors" tab logic, maybe something with [libpanel](https://gitlab.gnome.org/GNOME/libpanel)

![](https://github.com/GradienceTeam/Design/raw/main/Mockups/Gradience%20-%20Preset%20Manager%20V2.png)

**Comment by 0xMRTT** [comment]
Where do you want to add the quick switcher ?

**Comment by tfuxu** [comment]
> Where do you want to add the quick switcher ?

I think it could be just under Presets button as before.

**Comment by daudix-UFO** [comment]
> > Where do you want to add the quick switcher ?
> 
> I think it could be just under Presets button as before.

Yup👍

**Comment by 0xMRTT** [comment]
![image](https://user-images.githubusercontent.com/105598867/190008166-700d8de9-9934-4bdd-8450-27e275b1ba4b.png)

**Comment by 0xMRTT** [comment]
[Kooha-09-13-2022-23-16-42.webm](https://user-images.githubusercontent.com/105598867/190011252-3657590d-df19-4fb9-9b73-36fb89dc985d.webm)

**Comment by daudix-UFO** [comment]
Reopened because I don't want to open a bunch of other UI tweak issues

**Comment by 0xMRTT** [comment]
Ok 😎

**Comment by 0xMRTT** [comment]
![image](https://user-images.githubusercontent.com/105598867/190569501-0f5120d6-2a80-4eff-84cd-07bbc78fa396.png)

**Comment by daudix-UFO** [comment]
Wow 🔥

**Comment by tfuxu** [comment]
Another thing to add to the list:
![Screenshot from 2022-09-24 20-36-40](https://user-images.githubusercontent.com/73042332/192114895-5d28a249-2edb-4b04-88f1-5dbb92d3771d.png)
This explanation box doesn't have top and bottom paddings

**Comment by daudix-UFO** [comment]
Updated to-do

**Comment by 0xMRTT** [comment]
Tone isn't working ?

**Comment by daudix-UFO** [comment]
Yes, switching tone and pressing apply does nothing visually

**Comment by daudix-UFO** [comment]
[Запись экрана от 25.09.2022 23:47:12.webm](https://user-images.githubusercontent.com/77155297/192164941-5a7b91b0-d8e9-434a-b8fa-9fadee5b36cc.webm)

**Comment by 0xMRTT** [comment]
It's change the palette :D

**Comment by 0xMRTT** [comment]
![Uploading Screenshot from 2022-09-28 16-11-50.png…]()

**Comment by 0xMRTT** [comment]
![Screenshot from 2022-09-28 16-11-50](https://user-images.githubusercontent.com/105598867/192803363-c13ad3cb-7ddd-45e5-a429-97f7cb40782d.png)
om/105598867/192803322-18ba2128-8677-44b1-ba30-0ac1cec0a7b2.png)

**Comment by tfuxu** [comment]
> ![Screenshot from 2022-09-28 16-11-50](https://user-images.githubusercontent.com/105598867/192803363-c13ad3cb-7ddd-45e5-a429-97f7cb40782d.png)

Why would we need to show badges here? Wouldn't it be better to put a 'Remove preset' button here instead?

**Comment by 0xMRTT** [comment]
Or in the upper row instead of being in a submenu

**Comment by tfuxu** [comment]
![Screenshot from 2022-09-30 23-47-04](https://user-images.githubusercontent.com/73042332/193360824-7de5c51f-e9f0-4d6e-8d02-2b84ee36ed5e.png)
We should make this page more clear for a user, as there isn't any mention of it configuring Flatpak overrides, and `System configuration` can be confusing.

**Comment by 0xMRTT** [comment]
Yes, also Flatpak overriding isn't working

**Comment by daudix-UFO** [comment]
But in same time we need to keep it simple for the user

**Comment by 0xMRTT** [comment]
![Screenshot from 2022-10-02 21-48-32](https://user-images.githubusercontent.com/105598867/193473665-b2d45ff1-0709-4a09-ac94-acaee1f0dfcb.png)

**Comment by daudix-UFO** [comment]
.Devel icon shows now 🎉

**Comment by 0xMRTT** [comment]
Lol how 😅😀

**Comment by daudix-UFO** [comment]
I don't know, maybe one of tfuxu commits?

**Comment by tfuxu** [comment]
I didn't noticed that before but a fix for https://github.com/GradienceTeam/Gradience/issues/406#issuecomment-1257049286, added too much padding to other boxes:
![Screenshot from 2022-10-08 15-26-41](https://user-images.githubusercontent.com/73042332/194710005-c7375787-853c-47d2-9986-ca1bd480c61f.png)

**Comment by daudix-UFO** [comment]
0xMRTT is offline today so I will try to fix this

**Comment by daudix-UFO** [comment]
Alright, I think the padding is OK

**Comment by tfuxu** [comment]
> Alright, I think the padding is OK

I don't think so...
![Screenshot from 2022-11-17 18-45-03](https://user-images.githubusercontent.com/73042332/202519392-e34d39a3-e8e0-450f-aebb-204db449cc58.png)
![Screenshot from 2022-11-17 18-45-20](https://user-images.githubusercontent.com/73042332/202519404-ffdf9b70-ee92-441e-90a8-cb5efff4e7be.png)

**Comment by daudix-UFO** [comment]
Oops, you are right!

**Comment by daudix-UFO** [comment]
It kinda fixed now, the issue is that text is formatted in odd way

**Comment by gmagic** [comment]
What about Monet engine setting theme colors for Dinamic Wallpapers like Bing Wallpaper (extension) for example.

**Comment by daudix-UFO** [comment]
For this we will need a GNOME extension that will detect wallpaper change and will re-generate the theme, this is planned but there are no due date for this
