### ISSUE TITLE
bug: `@window_bg_color` is always opened on app launch

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The `@window_bg_color` is always open on application start

### To Reproduce

1. Open app
2. Scroll to `Header Bar Colors`

### Screenshots

![A bug](https://user-images.githubusercontent.com/77155297/190024796-cd3b997a-54ed-4f4f-8a47-567bca7b34c4.png)

### OS

Fedora Linux 36 (Silverblue Edition)

### Version

0.2.0

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Yes, it's normal. What value do you want ?

**Comment by daudix-UFO** [comment]
Not value, but make this value not active by default

**Comment by daudix-UFO** [comment]
Not a bug, it's a feature!
