### ISSUE TITLE
bug: update discord link

### ISSUE THREAD

**Issue by 0xMRTT** [GradienceTeam/Gradience#442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://discord.gg/MYa8Sr7btJ

### Installation method

Manual using meson - main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix-UFO** [comment]
Done, in all repos 😉

**Comment by 0xMRTT** [comment]
Thanks
