### ISSUE TITLE
bug: wrong presets download from preset manager

### ISSUE THREAD

**Issue by salarua** [GradienceTeam/Gradience#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Downloading presets from the preset manager consistently downloads the wrong preset under the name of the preset that was selected for download.

### To Reproduce

1. Open preset manager
2. Go to Explore tab
3. Download and apply a theme

### Expected behavior

The correct preset is downloaded.

### OS

Pop!_OS 22.04 LTS

### Version

0.2.2

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Fixed in v0.3.0
