### ISSUE TITLE
bug: theme applies only after a log out

### ISSUE THREAD

**Issue by LyesSaadi** [GradienceTeam/Gradience#501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Newly installed Gradience only applies themes after a first log out.

### To Reproduce

1. Install gradience for the first time
2. Override GTK3/4 themes
3. Apply a new preset
4. Nothing is applied
5. Log out and log in from GNOME Shell
6. Reapply the preset
7. It is applied

### Expected behavior

Overrides work without rebooting the session. Or, at least, users should be told to log out first.

### OS

Fedora Linux 36 (Workstation Edition)

### Version

0.3.0

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LyesSaadi** [comment]
Was this the first time I agreed to the Code of Conduct, btw xD ?

**Comment by ZechariahB** [comment]
Many applications do not know that a change to their GTK theme has occurred. Even in dconf, changing a theme via a setting does not always guarantee that other applications will be instantly themed. This goes for overrides as well. It's a very annoying issue in GNOME generally. This can usually be fixed after closing all instances of the offending application and starting a new one. If all applications don't change, this might be a sign ``~/.config/gtk-4.0`` or ``~/.config/gtk-3.0`` is missing. Please verify if you have both of them.

**Comment by 0xMRTT** [comment]
![image](https://user-images.githubusercontent.com/105598867/193473458-7b73572a-bcf0-43e0-aa44-28a2ad88fb94.png)
