### ISSUE TITLE
bug: welcome screen shows twice on fresh install

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Welcome screen shows twice

### To Reproduce

1. `flatpak uninstall --delete-data gradience`
2. `flatpak install gradience`

### Expected behavior

Full welcome screen on first install and short on update

### Screenshots

[Kooha-2022-09-25-23-01-40.webm](https://user-images.githubusercontent.com/77155297/192162993-9bcccc8d-1796-4e07-b338-ab96fe1643b0.webm)

### OS

Fedora Linux 36 (Silverblue Edition)

### Version

0.3.0

### Installation method

Flatpak from Flathub

### Additional context

This also happens on latest manual build

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
I think that i fixed it
