### ISSUE TITLE
bug: preset does not apply on Ubuntu (Flathub, 0.3.0)

### ISSUE THREAD

**Issue by BigCityCat** [GradienceTeam/Gradience#509]
### Issue

Gradience does not apply any saved preset. Log out or reboot. No preset can be applied. All settings are saved correctly. Flatseal settings used all applications. Using Adwaita.

### OS

Ubuntu Kinetic Kudu

### Version

0.3.0

### Installation method

Flatpak from Flathub

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by 0xMRTT** [comment]
Moved

**Comment by daudix-UFO** [comment]
> Yes these files do exist. I will say that I have been using the Material You Gnome Shell Extension with success. I have it switched off when using Gradience. When using the Gradience application the theme appears to be applied but will not apply to any other applications.

Can you try to remove this files and try again?

`rm -rf .config/gtk-4.0 .config/gtk-3.0`

**Comment by tfuxu** [comment]
Can be related: #501
Try to use reproducible steps from that issue, so we can figure out if both of those issues are related.

**Comment by ZechariahB** [comment]
I can only replicate this behavior when ``~/.config/gtk-4.0`` or ``~/.config/gtk-3.0`` is missing. When apply is initiated and these directories are missing, Gradience does not regenerate new ones and no theme is its result. In preferences, I also turned on GTK3 & GTK4 Flatpak theming. Flatpak application theming works as intended. Could it be a problem with Gradience flatpak preferences? Do they have them enabled?

Do non-flatpak GTK3 - GTK4 applications work? Are flatpak applications the only ones borked?

**Comment by tfuxu** [comment]
> I can only replicate this behavior when `~/.config/gtk-4.0` or `~/.config/gtk-3.0` is missing. When apply is initiated and these directories are missing, Gradience does not regenerate new ones and no theme is its result. In preferences, I also turned on GTK3 & GTK4 Flatpak theming. Flatpak application theming works as intended. Could it be a problem with Gradience flatpak preferences? Do they have them enabled?

Weird, because I've implemented directory creating back when I created this functionality, but honestly, I don't remember anymore how it all works exactly, so I can't tell you right now if this is the culprit of this issue. I'll check what can I do with this tomorrow.

**Comment by BigCityCat** [comment]
Sorry everyone. I have been working. I really appreciate your help. I noticed that after I switched the Material You extension off these files disappeared. After that I tried to set the preset using Gradience and it still would not apply the theme. I then checked to see if the files were created by gradeince and they were not in the folders. It looks as if The Material You extension is successful at creating the files but not gradience. Thank you

**Comment by BigCityCat** [comment]
Yes in preferences both GTk3 Flatpack and GTK 4 FlatPack theming are allowed. As well I have Flatseal and All Application other Files xdg-config are set for gtk3 and 4

**Comment by BigCityCat** [comment]
The only application being themed by gradience is the app itself. No other application will use the preset.

**Comment by BigCityCat** [comment]
Just verifying that it is now working properly. Thank you

**Comment by lgeurts** [comment]
Exactly same issue here.

**Comment by tfuxu** [comment]
> Exactly same issue here.

Which apps aren't themed on your system?

**Comment by busybox11** [comment]
Same issue here. Looks like there are no themed apps other than Gradience.

**Comment by tfuxu** [comment]
@busybox11 Do you have enabled Flatpak theming? Also, try to run Gradience from terminal and check if there aren't any errors showing up when applying a preset.

**Comment by busybox11** [comment]
@tfuxu Ahh, it does seem to have a problem. I'm not familiar with Flatpak, I did not know how to troubleshoot that properly.
The error I have is the following:
```
OSError: [Errno 30] Read-only file system: '/home/busybox/.var/app/com.github.GradienceTeam.Gradience/config/gtk-4.0/gtk.css'
```
I'm guessing this has something to do with app permissions. I tried enabling file system related permissions earlier today with Flatseal but apparently it didn't have an effect.
I'm going to try to troubleshoot and fix this by myself right now, and I'll keep you updated about it. Thanks!

**Comment by busybox11** [comment]
Tried again with the `git` variant AUR package.
It didn't work at first, though I did not have any errors in the console.
Then I disabled an extension, "Custom Accent Colors" (which I disabled earlier with the flatpak version as well), and now lo and behold, it works! I still have my accent color in the shell for some reason, but I won't complain.
Thank you for everything!
