### ISSUE TITLE
Firefox_gnome_theme plugin doesn't correctly theme the Firefox Gnome Theme

### ISSUE THREAD

**Issue by Raubion** [GradienceTeam/Gradience#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After the great 0.3.0-1 update with the plugin to theme Firefox Gnome Theme, I reapplied my custom color scheme. Upon opening the browser, I noticed that the buttons to close (both window and tab), minimalise en maximise are the wrong colour, even though regular gtk4 and gtk3 apps are themed correctly.  The ones currently applied are for a light theme, whereas my color scheme is a dark scheme. Changing the light or dark theme in Settings doesn't change this.

I also noticed I couldn't revert back and that reapplying the defaults would keep the Firefox Gnome Theme in the current colors. Upon use, I also noticed that some dropdown menus are transparent, which they weren't before. So I'm thinking this is related.

### To Reproduce

1. Go to gradience, apply theme with Firefox_gnome_theme plugin enabled
2. Go to Firefox
3. Notice wrong color buttons. 

Important: I cannot currently reproduce because Gradience won't override the current color scheme

### Expected behavior

The expected behavior is to correctly apply the color scheme, particularly the correct buttons. The transparent dropdown menus should also not be there

### Screenshots

![Schermafdruk van 2022-09-27 12-25-42](https://user-images.githubusercontent.com/35173208/192502785-73ebc4b0-58b6-43ce-b2ac-36102df5b9eb.png)

![Schermafdruk van 2022-09-27 12-19-08](https://user-images.githubusercontent.com/35173208/192502791-d3d9642f-2e06-4c5b-8c24-7cd3d11bbbcd.png)

![Schermafdruk van 2022-09-27 12-18-40](https://user-images.githubusercontent.com/35173208/192502793-92159129-2555-4718-995e-5e60ec9cdd2f.png)

### OS

Arch Linux

### Version

0.3.0-1

### Installation method

AUR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
It's fixed now.

**Comment by Raubion** [comment]
So I waited for the next release and in the meantime I also installed the firefox-gnome-theme release 105 which just came out two days ago, but still Gradience won't theme my firefox. I don't see other issues regarding this problem, so is it something in my setup? When I have the plugin enabled and I set any theme, it fully changes both libadwaita and gtk3 apps, but not the firefox theme.

Any tips?

**Comment by daudix-UFO** [comment]
I have this issue too, it will be fixed soon (I hope so)

**Comment by Raubion** [comment]
Might be related to the #626 commit regarding multiple profiles. In that case it would be fixed soon, as it is merged.
