### ISSUE TITLE
bug: When applying Headerbar background color, it also applies it to Calendar current week.

### ISSUE THREAD

**Issue by martinszeltins** [GradienceTeam/Gradience#548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I applied a custom Headerbar background color but it also changed the current week color in Calendar app _(see screenshot)_.

### Expected behavior

It should have only applied the color to the Headerbar and nothing else.

### Screenshots

![Screenshot from 2022-09-30 18-17-25](https://user-images.githubusercontent.com/34019878/193303935-4c520fe3-ebd1-4754-bd4e-ccf68712f4f1.jpg)

### OS

Fedora 37 Beta

### Version

0.3.0

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
That's not an issue with gradience but with GNOME Calendar

**Comment by martinszeltins** [comment]
> That's not an issue with gradience but with GNOME Calendar

I don't understand, how? Is the headerbar somehow related to other elements?

**Comment by 0xMRTT** [comment]
https://matrix.to/#/#Gradience:matrix.org
