### ISSUE TITLE
bug: When Headerbar is changed to dark, inactive window Headerbar is blank

### ISSUE THREAD

**Issue by martinszeltins** [GradienceTeam/Gradience#549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I set a background and foreground color for Headerbar but now all the headerbars on inactive windows look almost blank (cannot read even the window title). Perhaps there should be a way to customize how the headerbar looks on inactive windows or this is a bug.

### Screenshots

![headeb](https://user-images.githubusercontent.com/34019878/193306480-d769cacb-3ebc-43cf-89b5-b24a02ec64f6.jpg)

### OS

Fedora 37 Beta

### Version

0.3.0

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
https://matrix.to/#/#Gradience:matrix.org
