### ISSUE TITLE
bug: Extension Manager does not respect colors.

### ISSUE THREAD

**Issue by martinszeltins** [GradienceTeam/Gradience#550]
### Temporary fix

This is a bug with flatpaks and a temporary fix is to run this command:

````
$ sudo flatpak override --filesystem=xdg-config/gtk-4.0
````

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have found that the Extension Manager app does not respect the custom colors that are applied. And from what I can tell - it looks like Extension Manager is made using libadwaita, so it should work.

### Screenshots

![extensmanager](https://user-images.githubusercontent.com/34019878/193308764-0b22819d-a93d-4cf8-98f9-cfbb01ac511d.jpg)

### OS

Fedora 37 Beta

### Version

0.3.0

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Is it working with other apps ?

**Comment by 0xMRTT** [comment]
https://matrix.to/#/#Gradience:matrix.org

**Comment by martinszeltins** [comment]
> Is it working with other apps ?

Yes, all other libadwaita apps look fine.

**Comment by martinszeltins** [comment]
This is a bug with flatpaks and a temporary fix is to run this command:

````
$ sudo flatpak override --filesystem=xdg-config/gtk-4.0
````
