### ISSUE TITLE
bug: Themes are not applied to Gradience and some of the apps on Manjaro.

### ISSUE THREAD

**Issue by eboye** [GradienceTeam/Gradience#563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrade to 0.3.0 the app itself looks broken and like GTK3 app in light only mode no matter what settings I choose.

It's installed as flatpak app as aur version does not want to install as it says the libdwaita 1.2 alpha dep is needed? I'm on Manjaro Sikaris.

### To Reproduce

I've tried enabling and disabling GTK4 and GTK3 Flatpak themeing, tried deleting ~/.config/gtk-* folders, uninstalling and then again installing the Gradience app, nothing happens. It's recreating the folders, apps like Nautilus, Firefox etc works ok (non flatpak apps).

I've tried resetting permission to xdg-config/gtk-3.0 and 4 via flatseal and via CLI, but no affect.

### Expected behavior

Applying any other theme

### Screenshots

![image](https://user-images.githubusercontent.com/624357/193432734-a569aab8-7881-4482-b938-82565a7f37fe.png)

![image](https://user-images.githubusercontent.com/624357/193432805-c6a146e6-3be6-4e88-bb33-121d96686b3c.png)

![image](https://user-images.githubusercontent.com/624357/193432816-86dbcf03-ad81-4424-9e25-e4688b255434.png)

![image](https://user-images.githubusercontent.com/624357/193432828-654f448c-66bd-4576-bf28-ef8ad381e6f0.png)

### OS

Manjaro Linux Sikaris 22.0.0

### Version

0.3.0

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Do you have an other theme enabled ?

**Comment by tfuxu** [comment]
Such a weird bug...
Does Gradience shows any error messages while running in terminal?

**Comment by eboye** [comment]
@tfuxu well, there are some, bunch of warnings about unknown rule @define-color and this on start:

```log
WARNING	CSSStylesheet: Unknown @rule found. [23:1: @define-color]
[WARNING] [CSSUTILS] CSSStylesheet: Unknown @rule found. [23:1: @define-color]
ERROR	CSSUnknownRule: No ending ";" or "}" found: '@define-color headerbar_backdrop_color @window_bg_color;'
[ERROR] [CSSUTILS] CSSUnknownRule: No ending ";" or "}" found: '@define-color headerbar_backdrop_color @window_bg_color;'
WARNING	CSSStylesheet: Unknown @rule found. [24:1: @define-color]
[WARNING] [CSSUTILS] CSSStylesheet: Unknown @rule found. [24:1: @define-color]
```

After that, nothing ... 

I tried opening it before via CLI, but I didn't think it was worth mentioning as it didn't seem relevant. Maybe it is?

**Comment by 0xMRTT** [comment]
Css warning aren't important, that's normal :/

**Comment by eboye** [comment]
One more thing, it looks like it's not saving settings after a restart of the app.

[Kooha-2022-10-03-02-41-22.webm](https://user-images.githubusercontent.com/624357/193484011-832a4826-3fcd-40bc-a2e0-d4238743e3fc.webm)

Maybe some permission somewhere? Where does the app store it's settings? What permissions should it have?

**Comment by eboye** [comment]
In ~/.var/app/com.github.GradienceTeam.Gradience/config/gtk-4.0

it looks like these

```
drwx------ eboye eboye 4.0 KB Sun Oct  2 02:43:34 2022 glib-2.0
drwxr-xr-x eboye eboye 4.0 KB Sun Oct  2 02:43:34 2022 gtk-3.0
drwxr-xr-x eboye eboye 4.0 KB Sun Oct  2 02:43:34 2022 gtk-4.0
drwxr-xr-x eboye eboye 4.0 KB Sun Oct  2 02:43:35 2022 presets
```

And those gtk folders are empy

**Comment by 0xMRTT** [comment]
Did you followed the setup described in the README?

**Comment by eboye** [comment]
Yes

**Comment by tfuxu** [comment]
Do you maybe have Eyedropper installed as Flatpak too?

**Comment by eboye** [comment]
Yes, it's installed via flatpak. Flatpak apps are not styled, that is the problem. Or does it conflict in some way?

**Comment by tfuxu** [comment]
Okay, so this isn't a issue with Gradience explicitly.

It looks for me like a broken installation of GNOME runtime.
You could try updating GNOME runtime 42 to the newest version:
```
flatpak update org.gnome.Platform//42
```
or reinstalling:
```
flatpak remove org.gnome.Platform//42
flatpak install org.gnome.Platform//42
```
If this isn't it, then maybe a flatpak/filesystem permission issue?
You should report this to flatpak repository, maybe they'll have some more knowledge on how to fix this: https://github.com/flatpak/flatpak/issues

**Comment by 0xMRTT** [comment]
Hi,

What about trying the AUR package? 

Maybe that can solve your problem?

**Comment by tfuxu** [comment]
I'm closing this issue for now, because from what we've deducted, it's related to Flatpak bug, not to Gradience explicitly, but if it turns out later that Gradience is indeed a culprit of this issue, we can at any moment reopen this.

**Comment by tfuxu** [comment]
> Hi,
> 
> What about trying the AUR package?
> 
> Maybe that can solve your problem?

Yes it will, but only for Gradience.

**Comment by eboye** [comment]
finally I found what was causing it.

FlatSeal for some reason saved settings to ~/.local/share/flatpak/overrides at some point ... removing that folder solved all the issues.

**Comment by tfuxu** [comment]
> finally I found what was causing it.
> 
> FlatSeal for some reason saved settings to ~/.local/share/flatpak/overrides at some point ... removing that folder solved all the issues.

Ah, yes 😂️ I forgot to tell you the most obvious thing to do in order to fix broken Flatpak config. You could do exactly what you did, or just type in terminal: `flatpak override --reset`
Anyway, great that you found a solution for this!
