### ISSUE TITLE
bug: Flatpak apps dont get themed fully

### ISSUE THREAD

**Issue by sid314** [GradienceTeam/Gradience#569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Only window decorations get themed for flatpak apps

### To Reproduce

1. Apply theme
2. Open Flatpak app (say extension manager of flatseal)
3. Only window decorations get themed

### Expected behavior

Flatpak apps should be themed.
The temporary fix mentioned in other issues did not work.

### OS

Fedora Linux 36 (Workstation Edition)

### Version

0.3.0

### Installation method

Fedora COPR (lyessaadi/gradience)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Did you tried to override using the command described in the README ?

**Comment by sid314** [comment]
oops l missed the last part. Now it works . Thanks
