### ISSUE TITLE
Check if all contributors are listed in about window

### ISSUE THREAD

**Issue by 0xMRTT** [GradienceTeam/Gradience#593]
## Developers
  0xMRTT https://github.com/0xMRTT
  Artyom Fomin https://github.com/ArtyIF
  Tfuxu https://github.com/tfuxu
  Verantor https://github.com/Verantor
            
## Artists
  David Lapshin https://github.com/daudix-UFO

## Designers
  David Lapshin https://github.com/daudix-UFO
            

## Translator
  0xMRTT https://github.com/0xMRTT
  Aggelos Tselios https://www.transifex.com/user/profile/AndroGR
  BritishBenji https://github.com/BritishBenji
  Bittin https://github.com/bittin
  David Lapshin https://github.com/daudix-UFO
  Davide Ferracin https://github.com/phaerrax
  Ewout van Mansom https://github.com/emansom
  FineFindus https://github.com/FineFindus
  엘련(Jisu Kim) https://github.com/vbalien
  Juanjo Cillero https://www.transifex.com/user/profile/renux918
  Karol Lademan https://www.transifex.com/user/profile/karlod
  K.B.Dharun Krishna https://github.com/kbdharun
  Philip Goto https://github.com/flipflop97
  Maxime V https://www.transifex.com/user/profile/Adaoh
  Monty Monteusz https://www.transifex.com/user/profile/MontyQIQI
  Renato Corrêa https://github.com/renatocrrs
  Rene Coty https://github.com/rene-coty
  Taylan Tatlı https://www.transifex.com/user/profile/TaylanTatli34
  Tfuxu https://github.com/tfuxu

### To add
- Korean: @vbalien
- Portugese: @renatocrrs
- English US: @BritishBenji 
- French: @rene-coty
- Tamil: @kbdharun 
- Swedish: Luna Jernberg @bittin
- Italian: @phaerrax
- Dutch: @emansom
- German: @rene-coty 
- Croatian: @muzena

## Plugins
  0xMRTT https://github.com/0xMRTT
  Apisu https://github.com/aspizu

## Packagers
  0xMRTT https://github.com/0xMRTT
  Lyes Saadi https://github.com/lyessaadi

**Comment by bittin** [comment]
You can add me by real name Luna Jernberg if thats not too much to ask?

**Comment by daudix-UFO** [comment]
@bittin Of course!

**Comment by bittin** [comment]
thx

**Comment by daudix-UFO** [comment]
Hopefully I not missed someone

**Comment by 0xMRTT** [comment]
I'm not sure if you added everyone in the to add list ?
