### ISSUE TITLE
Final tests and freeze

### ISSUE THREAD

**Issue by 0xMRTT** [GradienceTeam/Gradience#594]

**Comment by 0xMRTT** [comment]
I've tested on a fresh arch install and everything is working fine
- [x] flatpak override
- [x] preset manager

**Comment by 0xMRTT** [comment]
@daudix-UFO @tfuxu @LyesSaadi is Gradience working right for you ?

**Comment by tfuxu** [comment]
Everything's good, we can freeze it

**Comment by 0xMRTT** [comment]
Perfect :rocket:

**Comment by daudix-UFO** [comment]
Unfreezing for now

**Comment by daudix-UFO** [comment]
🧊 Freezing back, this time forever (hopefully)

**Comment by 0xMRTT** [comment]
forever
