### ISSUE TITLE
bug: touchpad page scroll not working in welcome screen

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Only first page can be swiped, others only by pressing a button

### Installation method

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tfuxu** [comment]
I don't know if this can cause issues, because it is set to `False` only for three pages, but try removing `.set_interactive()` properties in https://github.com/GradienceTeam/Gradience/blob/main/gradience/welcome.py#L122-L144 and check if it still persists.

**Comment by 0xMRTT** [comment]
If i disable that, user can swipe on each tab

**Comment by daudix-UFO** [comment]
Welcome screen swipe gone brr
