### ISSUE TITLE
feat: GNOME Shell Theming

### ISSUE THREAD

**Issue by zPhoeniqz** [GradienceTeam/Gradience#618]
### Feature description

Option to apply color scheme from Gradience to GNOME Shell, e.g.:
* Panel
* Notification Center
* Dialog Windows
* The drop-down menu containing options like shutdown or logout (Screenshot in the 'Additional Context' section)
 

### Additional Context

Example where the color scheme would be applied:
![image](https://user-images.githubusercontent.com/72757232/194775039-4f440f46-9674-4341-b5a2-c4134f17d40b.png)

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment]
This is WIP 😉

**Comment by zPhoeniqz** [comment]
Oh, that's so nice to hear! Shoould I close this then?

**Comment by daudix-UFO** [comment]
I will keep this open for others to see progress 🙃

**Comment by daudix-UFO** [comment]
Tracked in GradienceTeam/Plugins

https://github.com/GradienceTeam/Plugins/issues/11

**Comment by talwat** [comment]
I also would really like this

**Comment by tfuxu** [comment]
@talwat 
If you are interested, you can check the progress of a PR that will add this feature here: #679
