### ISSUE TITLE
bug: Custom CSS for GTK3 does not work

### ISSUE THREAD

**Issue by zehkira** [GradienceTeam/Gradience#620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I was editing my theme. I added this to GTK3 custom CSS:
```css
.ssd .titlebar {
    min-height: 46px;
}
```
I saved the preset and applied it. But my CSS had no effect. It also disappeared from the custom CSS box.

### To Reproduce

1. Pick GTK3 in custom CSS
2. Add some CSS
3. Save the preset
4. Apply the preset
5. The custom CSS is gone

### Expected behavior

The custom CSS is saved along with the preset, and works correctly by making all app titlebars the same height.

### Screenshots

![image](https://user-images.githubusercontent.com/111002801/194853186-5ca04751-e883-425d-a95c-ca4c0c886e85.png)

### OS

Arch Linux

### Version

0.3.1

### Installation method

Flatpak from Flathub

### Additional context

The CSS here works fine when manually added to `./config/gtk-3.0/gtk.css`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tfuxu** [comment]
We would need to refactor a preset loading mechanism to fix this bug. At first glance it might seem that there is a simple way to fix this, just load simultaneously a CSS file for GTK 3 and 4, but what if a user doesn't want to theme GTK 3 apps? CSS rules won't be copied to GTK 3 config directory, and Gradience will have no idea, what rules are for GTK 3, which results currently in `list index out of range` error.

As a temporary fix, I would suggest to disable a GTK 3 option in dropdown menu, if the preset was loaded from a CSS file, or show message box informing the user that he needs to load a preset from preset manager to change GTK 3 CSS code.

**Comment by AzracStudios** [comment]
I had a similar issue. To fix it, I modified the css directly on the json theme files. It should be at ```~/.config/presets/```. You can check all the three folders for your theme. At the very end, you will find the custom CSS. When I added css from the app, the changes were not reflected on the respective json file. Adding it directly to the file fixed the issue for me

**Comment by daudix-UFO** [comment]
Can't reproduce in `shell-theming` branch

[Запись экрана от 2023-04-14 05-34-18.webm](https://user-images.githubusercontent.com/77155297/231927275-39433ee1-dc11-42d2-bbaa-12903be8a90c.webm)

![Снимок экрана от 2023-04-14 05-35-35](https://user-images.githubusercontent.com/77155297/231927304-7ba5641b-bcdb-4cde-b373-554c50e3d849.png)
