### ISSUE TITLE
bug: Log out button does not work on Ubuntu and it's derivatives

### ISSUE THREAD

**Issue by marcinjahn** [GradienceTeam/Gradience#621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I apply a theme, a modal is shown asking me to log out. When I click the "Log out" button, nothing happens. Gradience stays open, and log out operation does not proceed.

### To Reproduce

1. Choose a theme
2. Apply
3. Click Logout

### Expected behavior

I should be logged out and see the login screen.

### Screenshots

![image](https://user-images.githubusercontent.com/10273406/194896295-423a47fa-a479-4f7c-91b5-96d50f661340.png)

### OS

Fedora Linux 36 (Workstation)

### Version

0.3.1

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jfvillablanca** [comment]
Hello, I'm on PopOS 22.04. Same issue. Tried your suggestion of resetting app permissions using Flatseal. However, the Reset button is grayed out. Might be because I installed Gradience with a local file download from FlatHub and not thru Pop Shop

**Comment by daudix-UFO** [comment]
If the button is gray that means permissions are OK, so it needs to be solved

**Comment by daudix-UFO** [comment]
Tested on Ubuntu 22.10, issue is here, and issue on Ubuntu's side

**Comment by daudix-UFO** [comment]
[📎 gradience-ubuntu-22-10.log](https://github.com/GradienceTeam/Gradience/files/10041352/gradience-ubuntu-22-10.log)

**Comment by RafaelKr** [comment]
Same on Linux Mint 21 (Ubuntu 22.04 based)

**Comment by daudix-UFO** [comment]
I believe this also happens on elementary OS, so it means this is Ubuntu and all distros based on it have this issue, will look if debian have this issue or not

**Comment by RafaelKr** [comment]
Also if I logout manually the theme is not applied afterwards. Not sure if it is related to this.
When I check with `Flatseal` both permissions `xdg-config/gtk-3.0` and `xdg-config/gtk-4.0` were set from Gradience correctly. Also no reboot helps.

**Comment by daudix-UFO** [comment]
Hmm, for me it works in VM

**Comment by daudix-UFO** [comment]
@RafaelKr do you have xdg-desktop-portal installed?

`sudo apt install xdg-desktop-portal xdg-desktop-portal-gtk`

**Comment by daudix-UFO** [comment]
Ah, found the solution! issue was in missing dbus flatpak permission

**Comment by RafaelKr** [comment]
> @RafaelKr do you have xdg-desktop-portal installed?
> 
> `sudo apt install xdg-desktop-portal xdg-desktop-portal-gtk`

Yes

```
xdg-desktop-portal-gtk is already the newest version (1.14.0-1build1).
xdg-desktop-portal is already the newest version (1.14.4-1ubuntu2~22.04.1).
```

**Comment by daudix-UFO** [comment]
Bug is fixed, fix will land in next release :rocket:

**Comment by RafaelKr** [comment]
Will you release it now or is there an estimate release date? :)

**Comment by daudix-UFO** [comment]
I hope to release it as fast as possible, but all depends on the rest of the team ;)

**Comment by RafaelKr** [comment]
Ah, I see, you did the change to the flathub Repo :) Thanks a lot!

**Comment by daudix-UFO** [comment]
No problem!

(I don't know why build is failing xD)

**Comment by daudix-UFO** [comment]
Oh, you are right
