### ISSUE TITLE
bug: can't delete downloaded presets

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [GradienceTeam/Gradience#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Removing a downloaded preset fails with the message "Unable to delete preset"

### To Reproduce

1. open the preset manager
2. expand a downloaded preset
3. click on "Remove preset"

### Expected behavior

Preset should be deleted

### Screenshots

[preset deletion.webm](https://user-images.githubusercontent.com/15961647/194930164-20763829-c539-426f-be8b-9c43dc9f9ed6.webm)

### OS

Fedora Linux 36 (Workstation Edition)

### Version

0.3.1

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
@daudix-UFO where presets are stored in Flatpak ?

**Comment by tfuxu** [comment]
`/HOME_DIR/.var/app/com.github.GradienceTeam.Gradience/config/presets`

**Comment by daudix-UFO** [comment]
I have same issue

**Comment by 0xMRTT** [comment]
#628 fixed that

**Comment by mystrdat** [comment]
Still doesn't work for me on 0.3.1.

**Comment by tfuxu** [comment]
> Still doesn't work for me on 0.3.1.

That's because we didn't released a new version yet. Check the checklist in PR #632 from time to time, to see when the next version will be out.
