### ISSUE TITLE
bug: Gradience always saves custom presets as "User.json".

### ISSUE THREAD

**Issue by rayferric** [GradienceTeam/Gradience#624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Like in the title, Gradience always saves custom presets as `User.json`, even though it announces to do otherwise. This breaks user experience because it's not possible to save a second preset without removing the previous one, even under a different name. The problem occurs in Gradience version 0.3.1-2 provided by package `gradience` from the Arch Linux User Repository.

### To Reproduce

1. Install `gradience` from the AUR.
2. Save a custom preset under a name "My Custom Preset".
3. Navigate to `~/.config/presets/user` just to find a single file named `User.json`.

### Expected behavior

It is expected for the file to be named `my-custom-preset.json`.

### Screenshots

![Screenshot from 2022-10-10 22-06-52](https://user-images.githubusercontent.com/63957587/194944245-3bb20a8d-9211-45f0-a8ee-2dde244e2652.png)

### OS

Arch Linux

### Version

0.3.1-2

### Installation method

AUR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix-UFO** [comment]
This can be related to #623

**Comment by 0xMRTT** [comment]
Fixed

**Comment by tfuxu** [comment]
Not yet fixed
