### ISSUE TITLE
CSS Parser doesn't work very well with custom css

### ISSUE THREAD

**Issue by 0xMRTT** [GradienceTeam/Gradience#631]
Known issue, it's something with CSS parser we are using in Gradience, it will only cause issues if you are changing something in preset, and it got loaded with those errors.

_Originally posted by @tfuxu in https://github.com/GradienceTeam/Community/issues/56#issuecomment-1273653872_

**Comment by tfuxu** [comment]
Fixed in d554261863744c6d14c3bf9d9299f611a97e74fe
