### ISSUE TITLE
feat: Reset first run dialogue

### ISSUE THREAD

**Issue by jdamboeck** [GradienceTeam/Gradience#663]
### Feature description

I deleted .local/share/gradience and searched for every other file/folder with gradience in its name but i cant get the first run dialogue to appear again.

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment]
I will add instructions in the README, meantime you can uninstall Gradience with all it's data using `flatpak uninstall --delete-data com.github.GradienceTeam.Gradience`

### Note that this will also removeball your presets

**Comment by jdamboeck** [comment]
I do not use the flatpak.

**Comment by jdamboeck** [comment]
Where would you store user information else than in the user directory?

**Comment by daudix-UFO** [comment]
https://github.com/orgs/GradienceTeam/discussions/645

**Comment by 0xMRTT** [comment]
It's stored in dconf, just reset the key com.github.gradienceteam.gradience.first-run to true and re open gradience.

**Comment by jdamboeck** [comment]
> https://github.com/GradienceTeam/discussions/645
page not found

**Comment by daudix-UFO** [comment]
Done!

https://github.com/GradienceTeam/Gradience#show-welcome-window-again
