### ISSUE TITLE
feat: preset save dialog when switching to other preset via quick preset switcher

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#665]
### Feature description

Currently switching to other preset while editing first one just dismisses all changes, e.g I modify Pretty Purple, in the header bar unsaved button are displayed, when I switch to Adwaita Dark it just switches without aking me if I want to same my changes

There need to be same dialog as when closing window with not saved preset

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by tfuxu** [comment]
This one should be easy to implement, as it's just a matter of connecting the same check that we are using for a exit dialog to the preset load mechanism.
