### ISSUE TITLE
Approve Arabic Translations on Weblate 

### ISSUE THREAD

**Issue by Ali-x98** [GradienceTeam/Gradience#667]
### Feature description

I have finished the Arabic translation for Gradience on Weblate, though the changes for already approved strings require approval (they are marked as suggestions).

![image](https://user-images.githubusercontent.com/25479373/205336182-e61a0e48-7d7e-472d-9a55-da26cf97f38f.png)

The approved strings are mostly automatically translated. As such, they are not very well translated.

Also, I think it is better to not require approval for translations. This makes it so that already translated strings can be edited directly without requiring a reviewer's approval. From my experience, this is the case in other open-source projects.

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment]
شكرا كثيرا، انا رح اعمل هذا الان 👍

**Comment by Ali-x98** [comment]
Sure, though it is transliterated, not translated.

**Comment by daudix-UFO** [comment]
I see

**Comment by daudix-UFO** [comment]
Should be done now, tell me if not 😉

**Comment by Ali-x98** [comment]
It is, though it still shows that a review is required:
![image](https://user-images.githubusercontent.com/25479373/205346947-f75ddfc8-c28e-451d-a93c-9c5fab3275c3.png)

**Comment by Ali-x98** [comment]
btw, do you want "Gradience" to be transliterated, or should I keep it in English?

**Comment by daudix-UFO** [comment]
> btw, do you want "Gradience" to be transliterated, or should I keep it in English?

As you see it better

**Comment by daudix-UFO** [comment]
Hopefully this time everything OK

![image](https://user-images.githubusercontent.com/77155297/205348415-288c2a84-c7d4-426f-946a-053c51d7862e.png)

**Comment by Ali-x98** [comment]
Still, now the approved strings can not be edited. This is why I suggested not requiring approval.
![image](https://user-images.githubusercontent.com/25479373/205348821-60ad0ff4-8a9b-4807-ae51-62f1124bf579.png)

I think this makes it harder to fix mistakes, if there are any (there probably are).

**Comment by daudix-UFO** [comment]
Can you check again, I changed some settings

**Comment by Ali-x98** [comment]
Still cannot be edited.
![image](https://user-images.githubusercontent.com/25479373/205349713-5aeed837-e64c-4c13-b0a2-04e9f9891d61.png)

**Comment by daudix-UFO** [comment]
Checked using second account, now it works, sorry for inconvenience :sweat_smile:

**Comment by Ali-x98** [comment]
Yup, it's fixed now. Thank you.

**Comment by daudix-UFO** [comment]
No problem xD
