### ISSUE TITLE
feat: Add an Option to Select App Language

### ISSUE THREAD

**Issue by Ali-x98** [GradienceTeam/Gradience#674]
### Feature description

It would be great if the user has the freedom to choose the app's language rather than have it follow the system's language.

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by Ali-x98** [comment]
Ah, I see. So it is a Gnome limitation.

**Comment by daudix-UFO** [comment]
Likely yes, but as a translator I would like to see per-app locale setting in GNOME settings

**Comment by Ali-x98** [comment]
The thing is, I do not use Arabic as my system language because Gnome has an outdated and incomplete (and glitchy!) translation.

Any Idea about where I can take this feature request to?

**Comment by daudix-UFO** [comment]
Maybe https://gitlab.gnome.org/GNOME/gnome-control-center

**Comment by Ali-x98** [comment]
OK, Thank you.
