### ISSUE TITLE
bug: Some Flatpak applications are not themed

### ISSUE THREAD

**Issue by KaspianDev** [GradienceTeam/Gradience#682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Flatpak applications (Flatseal for example) do not match my gradience preset.

### To Reproduce

1. Install gradience & flatseal
2. Apply gradience preset
3. Open flatseal

### Expected behavior

Flatseal colors should be in dracula preset, as other applications

### Screenshots

![image](https://user-images.githubusercontent.com/34658474/209860169-c841df28-a472-4132-a9ca-3a355473828d.png)
![image](https://user-images.githubusercontent.com/34658474/209860217-6c372e10-5bd2-459c-a199-71a721146914.png)

### OS

Fedora 37

### Version

0.3.3

### Installation method

Flatpak from Flathub

### Additional context

I would like to add that yes I have checked "Allow gtk4 flatpak appplication theming".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix-UFO** [comment]
Have you logged out? Flatseal uses gtk3 so you need to check gtk3 checkbox in gradience settings

**Comment by KaspianDev** [comment]
Yup I logged out and in, I have all checkboxes checked in my settings
![image](https://user-images.githubusercontent.com/34658474/209860610-355040f9-ce2a-49d0-abbd-9cfb9a4f5bbf.png)
![image](https://user-images.githubusercontent.com/34658474/209860657-aabe5a4e-72c5-43be-bb89-08fcd4f90ec7.png)

**Comment by KaspianDev** [comment]
Update: Flatseal seems to be okay now, amberol is still the same though

**Comment by daudix-UFO** [comment]
Hmm, now this is odd, can you try `kill amberol` ?

**Comment by KaspianDev** [comment]
Oh you are right, sorry about that.

Now they only problematic apps are gparted and timeshift, and whats similar in them both is that they both run as root. Is there anything extra I need to do for them?

**Comment by daudix-UFO** [comment]
Root apps use root theme, which is not recommend to modify, also I believe you can use timeshift without root

Either way this can help: https://www.reddit.com/r/linuxmint/comments/mh1spr/comment/gswc9zv

**Comment by KaspianDev** [comment]
Thank you guys you are really helpful appreciate it!

**Comment by daudix-UFO** [comment]
I should add symlinking to the faq 😆
