### ISSUE TITLE
bug: Firefox is not affected after applying change of color (Ubuntu Firefox snap)

### ISSUE THREAD

**Issue by tfuxu** [GradienceTeam/Gradience#686]
### Discussed in https://github.com/orgs/GradienceTeam/discussions/685

<div type='discussions-op-text'>

<sup>Originally posted by **Boulotaur2024** January  1, 2023</sup>
I cannot seem to make that 'pure black color' go out of Firefox :

![Screenshot from 2023-01-01 16-51-49](https://user-images.githubusercontent.com/8013986/210176917-8bfd0d3a-6c17-40f7-b005-f976a9bdf5a3.png)

I want it to be 'Nordic' style just as Nautilus and the rest.
I don't know why it's not changing accordingly

My theme in Firefox is set to 'System Theme' :

![Screenshot from 2023-01-01 16-53-52](https://user-images.githubusercontent.com/8013986/210176938-a9cb1307-6829-4517-bb0d-4d4aa42b6ea0.png)

Not that it's a big deal but still...
Oh yeah I'm bored today..
Anyway thanks !

- Gradience 0.3.3 (Flatpak)
- Picked the 'Nordic Dark' user preset, applied it and then logged out</div>

**Comment by daudix-UFO** [comment]
I have reproduced it, that's because Firefox snap stores its data in `~/snap/firefox/common/.mozilla/firefox`, I don't know if we should officially support snap

Kinda related to #719
