### ISSUE TITLE
misc: Add docs about `gradience-cli`

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#697]
### Feature description

Currently we don't have any info about `gradience-cli` available to new user, so it would be nice to have ~~small note in README~~ docs about Gradience CLI interface, and info about available commands

### Additional Context

Part of #699

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by KCGD** [comment]
where did you find the package for gradience-cli? I cant seem to find it

**Comment by daudix-UFO** [comment]
`gradience-cli` is built-in Gradience, it will be available in the next release

**Comment by tfuxu** [comment]
This is related to #699 and will be included in initial user documentation.

**Comment by tfuxu** [comment]
Temporary documentation for CLI is available in repo's wiki: https://github.com/GradienceTeam/Gradience/wiki/Using-CLI

**Comment by tfuxu** [comment]
Closing, as CLI documentation is available in [docs](https://github.com/GradienceTeam/docs) repository and in published docs at https://gradience.readthedocs.io/en/latest
