### ISSUE TITLE
feat: Create user documentation

### ISSUE THREAD

**Issue by tfuxu** [GradienceTeam/Gradience#699]
### Feature description

Not much to say here, we just need to create a user documentation to unclutter our repository README, and to give users more info on some features.

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment]
We can do this by using GitHub wiki feature, so no need in separate website

**Comment by tfuxu** [comment]
GitHub wiki is quite limiting as it doesn't have many basic features most documentation software offers. I think it would be better to make docs on Read the Docs (basically Sphinx free hosting) or Gitbook.

**Comment by 0xMRTT** [comment]
I think that Sphinx is the best because that will allow us to document the code so i'm for the read the docs solution

**Comment by 0xMRTT** [comment]
![image](https://user-images.githubusercontent.com/105598867/212363733-19edea7f-c61d-496b-a2c8-eed8b6588839.png)

Let's go !!!

**Comment by 0xMRTT** [comment]
![image](https://user-images.githubusercontent.com/105598867/212384461-0305a52f-48e6-4f8a-b74a-386bc42a50cc.png)

**Comment by 0xMRTT** [comment]
I'm creating a pr for that so we can work together

**Comment by daudix-UFO** [comment]
LFG!

**Comment by 0xMRTT** [comment]
See #701 for progress on this

**Comment by tfuxu** [comment]
Check https://github.com/GradienceTeam/docs/issues/1 for a updated progress list.
