### ISSUE TITLE
bug: Adw-Gtk3 apps not themed.

### ISSUE THREAD

**Issue by Xyphyn** [GradienceTeam/Gradience#705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My theme won't apply on adw-gtk3. I use the adw-gtk3 theme like normal, and go to apply my theme. I check the checkbox, but when I apply it, nothing changes for gtk3 apps, even though libadwaita apps change like normal..

When running Gradience through the commandline, There is this error:
![image](https://user-images.githubusercontent.com/80978739/212988150-4e08dc36-1539-4600-ae50-c8003c14a96e.png)

### To Reproduce

1. Install adw-gtk3 theme
2. Open gradience and make your theme
3. Click "apply"
4. Check "GTK 3 apps"
5. cry that nothing happens

### Expected behavior

I expect the GTK-3 apps to be themed.

### OS

Fedora Linux 37 (Workstation Edition)

### Version

0.3.3

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tfuxu** [comment]
Which preset you used to reproduce this?

**Comment by Xyphyn** [comment]
My own.

**Comment by tfuxu** [comment]
Does it have some custom CSS or is it purely just different colors? Also, could you check in Flatseal if Gradience has `xdg-config/gtk-3.0` path allowed?

**Comment by Xyphyn** [comment]
It didn't, but enabling it made no difference. It can't open `~/.var/app/com.github.GradienceTeam.Gradience/config/gtk-3.0/gtk.css`, but allowing that path didn't work either.

**Comment by Xyphyn** [comment]
> Does it have some custom CSS or is it purely just different colors? Also, could you check in Flatseal if Gradience has `xdg-config/gtk-3.0` path allowed?

It's just different colors.

**Comment by daudix-UFO** [comment]
Maybe dumb question but… are you sure that you are using adw-gtk3?

**Comment by Xyphyn** [comment]
![image](https://user-images.githubusercontent.com/80978739/213012924-109a757a-aab7-46c1-ae7b-a7daaeef29fb.png)
Yep.

**Comment by 0xMRTT** [comment]
You need to allow access to .config/gtk-3.0 and .config/gtk-4.0 so gradience can modify files outside of the flatpak

**Comment by tfuxu** [comment]
> You need to allow access to .config/gtk-3.0 and .config/gtk-4.0 so gradience can modify files outside of the flatpak

This is exactly what `xdg-config/gtk-3.0` gives access to tho. This probably is a file permission issue inside a Gradience sandbox. @Xyphyn Try to reinstall Gradience, as this looks for me to be a Flatpak bug.

**Comment by Xyphyn** [comment]
I figured out the problem. For some reason, `gtk.css` was made with root as the owner.
