### ISSUE TITLE
bug: Theme Reset after log out

### ISSUE THREAD

**Issue by Corrupter-rot** [GradienceTeam/Gradience#711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I followed the steps. build libadwaita form source and did all the setup.
- When selecting and applying the preset, the preset is applied successfully.
- when restarting my laptop or logging out & logging in seems to reset gradience applied theme.
- Even locking and unlocking resets the theme applied by gradience.
System Specifications
```
OS: Nobara Linux 37 (Thirty Seven) x86_64 
Host: TUF Gaming FX705DT_FX705DT 1.0 
Kernel: 6.1.8-201.fsync.fc37.x86_64 
DE: GNOME 43.2 
WM: Mutter 
WM Theme: Adwaita 
Theme: adw-gtk3-dark [GTK2/3] 
Icons: McMuse-circle-dark [GTK2/3] 
Terminal: gnome-terminal 
```

### Expected behavior

Applied preset should have stayed and not automatically changed to default adwaita theme.

### OS

Nobara Linux 37 (Thirty Seven) x86_64 

### Version

0.3.3

### Installation method

Fedora COPR (lyessaadi/gradience)

### Additional context

Since nobara linux comes preinstalled with adw-gtk3. I just added the copr repo and updated the theme.

Also adw-gtk3 is in `/usr/share/themes`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix-UFO** [comment]
Can you disable "Custom Accent Colors" extension and delete the GTK config folders: `rm -rf .config/gtk-4.0 .config/gtk-3.0` (nautilus bookmarks will be removed, backup `bookmarks` file and put it back in if you want to save them) ?

**Comment by Corrupter-rot** [comment]
@daudix-UFO Thank You. It solved the issue.
