### ISSUE TITLE
bug: Preset source filter does not work properly with Russian locale

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In Preset Manager, in Explore tab, when switching the presets source from "All" to "Official" or "Curated" and then switching back to "All" causes in "No Results Found" page to appear, This happens when using Russian and probably other locales, this does not happen with English locale

### To Reproduce

1. Open Gradience in Russian using this command: `flatpak run --env=LANG=ru com.github.GradienceTeam.Gradience`
2. Open Preset Manager
3. Enter Explore tab
4. Switch from "All" to "Official" or "Curated"
5. Switch back to "All"
6. Look at placeholder

### Expected behavior

To switch back normally

### Screenshots

[Kooha-2023-02-05-22-11-11.webm](https://user-images.githubusercontent.com/77155297/216840075-48d590be-e19e-42d6-9663-f0decb2c3e8b.webm)

### OS

Fedora Linux 37 (Silverblue Edition)

### DE/WM version

GNOME 43.2

### Version

`main` branch

### Installation method

Flatpak from manual build

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tfuxu** [comment]
Did you got any errors while running Gradience in terminal?

**Comment by tfuxu** [comment]
I was able to reproduce this with Polish locale.

[Kooha-2023-02-06-00-35-36.webm](https://user-images.githubusercontent.com/73042332/216852559-169cf52f-4fe8-4e48-8751-b0b24e4affb7.webm)

I also found a culprit of this bug, I'll fix it when I'll have some spare time tomorrow.
