### ISSUE TITLE
feat: Temporary usage docs

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#716]
### Feature description

Small guide on how to use gradience, from installing adw-gtk3 to disabling broken extensions that are shipped with Nobara

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by tfuxu** [comment]
At that point, we could just finish the docs 0xMRTT started doing, as he already done installation and setup pages.

**Comment by daudix-UFO** [comment]
This would be good
