### ISSUE TITLE
bug: Monet doesn't work with non-English locale

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Trying to generate Monet palette while running Gradience with different locale (tested with Russian and Polish) than english does nothing, only changes palette preview and outputs this error:

```
[Gradience] WARNING: Custom preset not found. Fallback to Adwaita
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/gradience/frontend/views/main_window.py", line 125, in on_monet_file_chooser_response
    self.on_apply_button()
  File "/app/lib/python3.10/site-packages/gradience/frontend/views/main_window.py", line 221, in on_apply_button
    self.app.update_theme_from_monet(self.theme, self.monet_theme)
  File "/app/lib/python3.10/site-packages/gradience/frontend/main.py", line 379, in update_theme_from_monet
    preset_object = PresetUtils().new_preset_from_monet(monet_palette=monet,
  File "/app/lib/python3.10/site-packages/gradience/backend/theming/preset_utils.py", line 152, in new_preset_from_monet
    self.preset.new(variables=variable)
UnboundLocalError: local variable 'variable' referenced before assignment
```

### To Reproduce

1. Run Gradience with locale different from English from terminal
2. Open "Monet" tab
3. Generate palette from wallpaper
4. See the error output in terminal

### Expected behavior

A Monet palette to generate sucessfully

### Screenshots

![image](https://user-images.githubusercontent.com/77155297/221227472-b79c1a23-badb-4888-98e3-779c9f246f68.png)

### OS

Fedora Linux 37 (Silverblue Edition)

### DE/WM version

GNOME 43.3

### Version

0.4.0

### Installation method

Flatpak from Flathub

### Enabled system extensions (GNOME specific)

```
nightthemeswitcher@romainvigier.fr
color-picker@tuberry
appindicatorsupport@rgcjonas.gmail.com
clipboard-indicator@tudmotu.com
gsconnect@andyholmes.github.io
background-logo@fedorahosted.org
```

### Additional context

Maybe this happens because of translated labels in Monet theme variant switcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tfuxu** [comment]
I have a fix for this issue in Shell theming PR. I could backport it to upstream and then we could maybe release a hot-fix, so people with other locales don't have that issue ASAP.

**Comment by daudix-UFO** [comment]
Yeah, it would be good!

**Comment by tfuxu** [comment]
@daudix-UFO Fixed
