### ISSUE TITLE
bug: AttributeError: module 'PIL.Image' has no attribute 'Resampling' when trying to generate monet theme

### ISSUE THREAD

**Issue by duckyondiscord** [GradienceTeam/Gradience#728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This occurs both on the CLI and the GUI versions, and both the stable and git AUR packages.
Full log from the CLI app is below:
```Traceback (most recent call last):
  File "/sbin/gradience-cli", line 456, in <module>
    cli = CLI()
  File "/sbin/gradience-cli", line 121, in __init__
    self.__parse_args()
  File "/sbin/gradience-cli", line 154, in __parse_args
    self.generate_monet(args)
  File "/sbin/gradience-cli", line 353, in generate_monet
    palette = Monet().generate_from_image(_image_path)
  File "/usr/lib/python3.10/site-packages/gradience/backend/theming/monet.py", line 56, in generate_from_image
    (basewidth, hsize), monet.Image.Resampling.LANCZOS
  File "/home/ducky/.local/lib/python3.10/site-packages/PIL/Image.py", line 77, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
```

### To Reproduce

1. Open gradience
2. Click on the monet tab
3. Select an image

### Expected behavior

The monet theme is generated without problems like before. (exact working version unknown since it's been a while since I used it)

### Screenshots

![Screenshot of the output including the command](https://user-images.githubusercontent.com/94759537/221400971-07ed4225-0179-49b7-8819-a888187b25d0.png)

### OS

Arch Linux

### DE/WM version

Hyprland(also tested on GNOME 43)

### Version

0.4.0.r83.g40c4bf1a-1

### Installation method

AUR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
That's because you are using pil<9.

Otherwise it's Image.ANTIALiASING

**Comment by tfuxu** [comment]
@duckyondiscord Can you verify whether or not you are using Pillow in version 9 or higher?

**Comment by tfuxu** [comment]
Closing as OP hasn't responded in 3 weeks.
