### ISSUE TITLE
Theming is Broken in Pop!_OS 22.04

### ISSUE THREAD

**Issue by Raxelgrande** [GradienceTeam/Gradience#730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I installed Gradience and went through the set-up (ticking all the toggles to ON), then downloaded the Pop presets and applied Pop-dark. 

Then i logged out and logged in, but no change was made to other GTK3 & 4 programs (Gradience did keep the Pop-dark theming). 

I tried to remove Gradience (including .var files), reset flatpak permissions but nothing changed. 

### To Reproduce

1) Install latest Pop!_OS
2) Install Gradience and tick all the boxes in the set up 
3) Change the Gradience theme to Pop-dark 
4) Log out and log in 
5) Launch a GTK3 & 4 Flatpak app 
6) No theming found, it uses adwaita. 

### OS

Pop!_OS 22.04

### DE/WM version

Cosmic/Gnome 42

### Version

Latest 

### Installation method

Flatpak from Flathub

### Enabled system extensions (GNOME specific)

Cosmic Dock 
Cosmic Workspaces
Cosmic X11 Gestures
DING Desktop Icons NG
Pop COSMIC
Pop Shell 
System76 Power
Ubuntu AppIndicators

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tfuxu** [comment]
@Raxelgrande Please fill out `Enabled system extensions` section in your issue form.

**Comment by Raxelgrande** [comment]
@tfuxu Already did. Those are the default Pop Extensions, all of them are enabled.

**Comment by tfuxu** [comment]
Okay, does it only affect Flatpak apps or maybe native ones too?

**Comment by tfuxu** [comment]
Did you enabled Flatpak theming in Gradience preferences?

**Comment by Raxelgrande** [comment]
I enabled both the startup toggles and the toggles in preferences "enable gtk3/4 theming"

**Comment by tfuxu** [comment]
Hmm, check if you have `xdg-config/gtk-4.0` and `xdg-config/gtk-3.0` paths set in Flatpak overrides either by opening `/home/USER/.local/share/flatpak/overrides/global` file or in Flatseal.

**Comment by tfuxu** [comment]
Are there maybe set some additional allowed files or environment variables?

**Comment by Raxelgrande** [comment]
I did a flatpak override reset to test. 
Then re added xdg-config and nothing changed

**Comment by tfuxu** [comment]
Could you run Gradience through terminal and check if it gives any output during theme apply?

**Comment by Raxelgrande** [comment]
It gives no output with theme changing or enabling/disabling the theming toggles

**Comment by tfuxu** [comment]
Does this issue persists on every Flatpak apps you have installed? Also, did you log out after applying preset? You could also try removing whole `/home/USER/.local/share/flatpak/overrides` folder, as it can sometimes have some weird issues.

**Comment by Raxelgrande** [comment]
If you mean the flatpaks don't apply the theme, yes. 
I did log out after every change 
I removed the folder, logged out and nothing changed. The folder appeared again after the log-out

**Comment by Raxelgrande** [comment]
Im not even sure how, but i managed to fix the theming issue. 
I did this: 
1) remove flatpak using --purge option in apt 
2) delete .local flatpak folder 
3) reinstall gradience 
4) it works? gtk4 apps are themed with gradience and gtk3 is themed using the separate flatpak from the Pop!_OS team

The bug needs to get replicated to see if it was my system being dumb or a Pop!_OS issue, thanks for the support!

**Comment by tfuxu** [comment]
Thanks for the report, good to see that you eventually got it working properly. I will leave your issue open for now, as I'll try to reproduce this on a VM, and I will let you know about the results later.

**Comment by 0xMRTT** [comment]
@halfmexican any ideas ?

**Comment by halfmexican** [comment]
No ideas, I just did a fresh install of pop on an old lenovo, and I couldn't recreate the issue.

**Comment by tfuxu** [comment]
I also couldn't reproduce this issue. It looks like OP simply just had a broken Flatpak configuration.
