### ISSUE TITLE
bug: gradience deos not start

### ISSUE THREAD

**Issue by rellit** [GradienceTeam/Gradience#733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm on a freah gnome 43 install on arch linux.
Gradience installed via flatpak or via aur. Both versions do not start up at all.
journalctl sais this is because there is no ~/.config/gtk-4.0/gtkl.css.

That' right, there ist no such file. Just a settings.ini.

Gnome is indeed working and looks correct.

Wehn logging into a session with a freah created user, there is also no gtk.css. So i asume this is default behavior.

### To Reproduce

1. Install gnome on arch.
2. Try to launch gradience

### OS

Arch Linux

### DE/WM version

GNOME 43.3

### Version

0.4

### Installation method

Flatpak from Flathub

### Additional context

```
Mär 08 17:00:51 hq-arch systemd[983]: Started Application launched by gnome-shell.
Mär 08 17:00:51 hq-arch systemd[983]: Started app-flatpak-com.github.GradienceTeam.Gradience-7486.scope.
Mär 08 17:00:51 hq-arch com.github.GradienceTeam.Gradience.desktop[2639]: [Gradience] WARNING: Custom preset not found. Fallback to Adwaita
Mär 08 17:00:51 hq-arch com.github.GradienceTeam.Gradience.desktop[2639]: Traceback (most recent call last):
Mär 08 17:00:51 hq-arch com.github.GradienceTeam.Gradience.desktop[2639]:   File "/usr/lib/python3.10/site-packages/gradience/frontend/main.py", line 252, in load_preset_from_css
Mär 08 17:00:51 hq-arch com.github.GradienceTeam.Gradience.desktop[2639]:   File "/usr/lib/python3.10/site-packages/gradience/backend/css_parser.py", line 47, in parse_css
Mär 08 17:00:51 hq-arch com.github.GradienceTeam.Gradience.desktop[2639]: FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/home/tim/.config/gtk-4.0/gtk.css'
Mär 08 17:00:51 hq-arch com.github.GradienceTeam.Gradience.desktop[2639]: During handling of the above exception, another exception occurred:
Mär 08 17:00:51 hq-arch com.github.GradienceTeam.Gradience.desktop[2639]: Traceback (most recent call last):
Mär 08 17:00:51 hq-arch com.github.GradienceTeam.Gradience.desktop[2639]:   File "/usr/lib/python3.10/site-packages/gradience/frontend/main.py", line 148, in do_activate
Mär 08 17:00:51 hq-arch com.github.GradienceTeam.Gradience.desktop[2639]:   File "/usr/lib/python3.10/site-packages/gradience/frontend/main.py", line 279, in load_preset_from_css
Mär 08 17:00:51 hq-arch com.github.GradienceTeam.Gradience.desktop[2639]:   File "/usr/lib/python3.10/site-packages/gradience/frontend/main.py", line 307, in load_preset_from_resource
Mär 08 17:00:51 hq-arch com.github.GradienceTeam.Gradience.desktop[2639]:   File "/usr/lib/python3.10/site-packages/gradience/frontend/main.py", line 333, in load_preset_variables_from_preset
Mär 08 17:00:51 hq-arch com.github.GradienceTeam.Gradience.desktop[2639]:   File "/usr/lib/python3.10/site-packages/gradience/frontend/main.py", line 440, in reload_variables
Mär 08 17:00:51 hq-arch com.github.GradienceTeam.Gradience.desktop[2639]: TypeError: Gtk.CssProvider.load_from_data() takes exactly 3 arguments (2 given)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Neo-29** [comment]
Confiirmed.
Not starting
Archlinux

**Comment by tfuxu** [comment]
Related: #722
Are you sure you get the same tracebacks with Flatpak Gradience? 

Release from AUR doesn't work, because it hasn't been yet updated to 0.4.1 which has a patch for a new breaking change in GTK 4.10, but it doesn't seem right that Flatpak release would also have this issue, as it got a update to 0.4.1

**Comment by Neo-29** [comment]
I locally built with 0.4.1 on arch
Same issue.

**Comment by rellit** [comment]
Like i wrote, i tried both ways. Built with aur and tried flatpak.
Both Versions not starting

Am 8. März 2023 18:34:52 MEZ schrieb Neo-29 ***@***.***>:

**Comment by rellit** [comment]
Tried again, to check Versions.
Flathub lists Version 4.0 for me. Same as when i build gradience from AUR. When building gradience-git, I get Version 4.1 which starts up. So I think I will close this issue.

Thanks for your help

**Comment by tfuxu** [comment]
> Flathub lists Version 0.4.0 for me.

Ah yes, I've noticed that now, looks like I forgot to update project version before releasing 0.4.1 🤦‍♂️️. You should be able to return to stable Gradience AUR package soon, I'll notify package maintainers after I fix that problem with incorrect versioning. Thanks for reporting.

**Comment by Neo-29** [comment]
> > I locally built with 0.4.1 on arch
> > Same issue.
> 
> @Neo-29 I can't reproduce this after (and before) updating to GTK 4.10. Do you get `TypeError: Gtk.CssProvider.load_from_data() takes exactly 3 arguments (2 given)` error when trying to run Gradience?

Launching `gradience` in terminal returns nothing.
But no launch.

**Comment by tfuxu** [comment]
Try running it in debug mode by executing `local.sh` script

**Comment by Neo-29** [comment]
> Try running it in debug mode by executing `local.sh` script

This works.

**Comment by tfuxu** [comment]
What commands did you use to install Gradience? Here's a official guide for manual install via Meson: https://github.com/GradienceTeam/Gradience/blob/main/HACKING.md#global-installation

**Comment by Neo-29** [comment]
I told you, AUR first with actual version = broken
Then local pkgbuild with 0.4.1 = didn't work either 😔😉

**Comment by Neo-29** [comment]
Manual install from source should work as expected for sure.

**Comment by tfuxu** [comment]
> I told you, AUR first with actual version = broken Then local pkgbuild with 0.4.1 = didn't work either pensivewink

Oh okay, I thought you installed 0.4.1 right away using Meson

**Comment by Neo-29** [comment]
> > I told you, AUR first with actual version = broken Then local pkgbuild with 0.4.1 = didn't work either pensivewink
> 
> Oh okay, I thought you installed 0.4.1 right away using Meson

Nope.. KISS.. I try to use arch power first 💪😅

**Comment by pratyush-1327** [comment]
This issue still persists for me..Was it fixed?
I have tried both gradience and gradience-git from aur
