### ISSUE TITLE
bug: Pallet resets on logout

### ISSUE THREAD

**Issue by AzracStudios** [GradienceTeam/Gradience#734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The color pallet  that I select, is applied on first try. But when I logout and log back in (as recommended by the prompt) the pallet automatically resets to Adwaita

### To Reproduce

1. Install Gradience
2. Load a preset from community presets
3. Apply it
4. Logout and log back in

### OS

Manjaro Linux 22.0.4 Sikaris

### DE/WM version

Gnome 43.3, Wayland

### Version

0.4.0

### Installation method

AUR

### Enabled system extensions (GNOME specific)

1. Blur My Shell
2. Vitals
3. Pop shell
4. Compiz windows effect
5. App indicator support
6. Arc Menu
7. Custom accent colors
8. Dash to dock
9. Drive menu
10. Gnome ui tune
11. Gsconnect
12. Native window placement
13. Pamac updates
14. Screenshot window sizer
15. User theme
16. X11 Guestres

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tfuxu** [comment]
Disable `Custom accent colors` extension and retry preset apply

**Comment by AzracStudios** [comment]
Thanks! that works!! Oh and another thing (I probably should be creating another bug report, but just for the time being), why isn't gradience affecting the extension popups (access center, vitals etc.) ??

**Comment by tfuxu** [comment]
> why isn't gradience affecting the extension popups (access center, vitals etc.) ??

Because it is currently a GTK-only customization tool, but PR #679 (which is finally almost finished) will bring up customization for GNOME Shell, which in turn will also customize all your extensions.
