### ISSUE TITLE
bug: Some apps are not themed

### ISSUE THREAD

**Issue by heschy2** [GradienceTeam/Gradience#738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The majority of apps uses the Gradiance-Theme I created but some apps ignore it.

For example:
- GNOME Lollypop `(org.gnome.Lollypop)`
- Lutris `(net.lutris.Lutris)`
- Formiko `(cz.zeropage.Formiko)`
- Wike `(com.github.hugolabe.Wike)`
- ...

They all are flatpaks, but I also have some Flatpaks that use the Theme:
- Collision `(dev.geopjr.Collision)`
- Elastic `(app.drey.Elastic)`

So, the fact that they all are flatpaks should be irrelevant, but who knows...

I have no Idea why some Apps are using it and some not.

### To Reproduce

1. Create a theme
2. Apply it
3. Restart Session / Restart PC
4. Open Lollypop

### Expected behavior

The Theme is used in all (GTK) apps.

### Screenshots

A Flatpak that uses the Theme (elastic)
![Bildschirmfoto vom 2023-03-14 17-15-47](https://user-images.githubusercontent.com/105609148/225069510-d8d426c8-0af8-4826-98bf-94fdc2efdca7.png)

The Flatpak access is enabled:
![Bildschirmfoto vom 2023-03-14 17-10-18](https://user-images.githubusercontent.com/105609148/225067924-96da19b9-214e-4f62-b913-d0ad08859918.png)

A Flatpak that doe not use the theme: (Lollypop):
![Bildschirmfoto vom 2023-03-14 17-04-06](https://user-images.githubusercontent.com/105609148/225072849-70086882-4a48-4e30-936b-2e74e275063c.png)

GNOME Control Center uses the theme:
![Bildschirmfoto vom 2023-03-14 17-43-58](https://user-images.githubusercontent.com/105609148/225077014-59dfec8d-6d5d-4853-98df-0a78ba7c14b3.png)

### OS

openSUSE Tumbleweed

### DE/WM version

GNOME 44.rc

### Version

0.4.1 stable

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tfuxu** [comment]
Make sure you are also theming adw-gtk3 apps, because all of unthemed apps you mentioned are written in GTK3.
