### ISSUE TITLE
bug: Firefox has glitches

### ISSUE THREAD

**Issue by heschy2** [GradienceTeam/Gradience#739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Everytime I have more than 3 tabs open, tha Tabbar is switching between 'has arrows' and 'has no arrows' multiple times each second, pinned tabs are not affected.
It is abolutley anoying, I already hat this bug on Ubuntu 22.10, and now I have it on Tumbleweed.
But the fact that it already was on ubuntu indicates that it is not a problem of gradience, because gradience hat no effect on the Snap version of Firefox, although, gradience edits the theme, so gradience could repair it.

Also the popup menus in firefox have a transparent background, wich sometimes make them completley unusable, this did not happen on Ubuntu, that might be an indicator that it is a problem of gradience.

### To Reproduce

1. Install the Firefox Theme
2. Make Firefox use the Theme
3. Make your own theme using gradience
4. Open Firefox

### Expected behavior

If there aren't enough tabs to scroll, there should be no arrows.
If there are enough tabs (or now enought space) to scroll, they should apear, but only then.

### Screenshots

Tabbar
[firefox_glitch.webm](https://user-images.githubusercontent.com/105609148/225087107-721f5b6b-ad58-428e-9037-f9d7e3a3619a.webm)

Context Menu
![Bildschirmfoto vom 2023-03-14 18-22-43](https://user-images.githubusercontent.com/105609148/225087345-254db514-8560-4831-8352-b5b8446dac7c.png)

Hamburger Menu > Help
![Bildschirmfoto vom 2023-03-14 18-26-19](https://user-images.githubusercontent.com/105609148/225088185-1a35de91-b327-4c7a-9927-bb3565bb1626.png)

### OS

openSUSE Tumbleweed (and Ubuntu 22.10)

### DE/WM version

GNOME 44.rc (on Tumbleweed) and Gnome 43 (on Ubuntu)

### Version

0.4.1 stable

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix-UFO** [comment]
> But the fact that it already was on ubuntu indicates that it is not a problem of gradience, because gradience hat no effect on the Snap version of Firefox, although, gradience edits the theme, so gradience could repair it.

Apparently it have been fixed, see https://github.com/rafaelmardojai/firefox-gnome-theme/issues/596
