### ISSUE TITLE
bug: Windows decoration on adw-gtk3

### ISSUE THREAD

**Issue by Giovannimbesi25** [GradienceTeam/Gradience#740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?
![Schermata del 2023-03-19 21-46-36](https://user-images.githubusercontent.com/94128698/226208026-e00cd784-0a3a-4ac6-9f5d-ca3f91673cd2.png)

When I use Pop-dark preset, libadwaita apps are correctly themed, while gtk3 and gtk4 apps ,  have the right colors but wrong windows decoration.

N.B: For legacy applications I'm using adw-gtk3 theme from https://github.com/lassekongo83/adw-gtk3.

### To Reproduce

1. Download and set adw-gtk3 theme for legacy applications
2. Apply Pop-dark preset on Gradience

### Expected behavior

Pop-dark default windows decoration on all apps

### OS

Pop_Os

### DE/WM version

Gnome 42

### Version

0.4.0

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Is it related to the preset or not ? Could you send us a screenshot?

**Comment by Giovannimbesi25** [comment]
> Is it related to the preset or not ? Could you send us a screenshot?

I've added a screenshot

**Comment by Giovannimbesi25** [comment]
I've added a screenshot

**Comment by Giovannimbesi25** [comment]
I've added a screenshot

**Comment by daudix-UFO** [comment]
This is expected behavior, pop preset is being created with using it with original pop theme in mind, adw-gtk3 simply don't have configuration for this

**Comment by Giovannimbesi25** [comment]
> This is expected behavior, pop preset is being created with using it with original pop theme in mind, preset doesn't have adw-gtk3 support

Okay, thanks for the info, I'll close the issue.
