### ISSUE TITLE
bug: theme not getting applied to some apps, including Gradience itself

### ISSUE THREAD

**Issue by IvoryJam** [GradienceTeam/Gradience#744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After some flatpak updates, Gradience no longer themes itself as well as other apps like com.mattjakeman.ExtensionManager and de.haeckerfelix.Fragments. 

It's not all flatpak apps though, firefox and clapper follow the theme just fine

### To Reproduce

1. Open Gradience

### Expected behavior

To theme all applications

### Screenshots

![image](https://user-images.githubusercontent.com/35709713/227736069-8fa6276b-e90e-49aa-9d08-2d0fe2eab330.png)

### OS

Fedora Linux 37 (Workstation Edition)

### DE/WM version

GNOME 43.3, Mutter

### Version

0.4.1

### Installation method

Flatpak from Flathub

### Enabled system extensions (GNOME specific)

AlphabeticalAppGrid@stuarthayhurst
blur-my-shell@aunetx
caffeine@patapon.info
dash-to-dock@micxgx.gmail.com
ddterm@amezin.github.com
io.github.mreditor.gnome-shell-extensions.scroll-panel
just-perfection-desktop@just-perfection
middleclickclose@paolo.tranquilli.gmail.com
rounded-window-corners@yilozt

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IvoryJam** [comment]
I am also using adw-gtk3 installed via the copr repo

**Comment by tfuxu** [comment]
<sub>Why does so many people has this issue...</sub>
Could you please post here your `~/.local/share/flatpak/overrides` file?

**Comment by daudix-UFO** [comment]
also, do you use any gtk4 themes?

**Comment by IvoryJam** [comment]
There is only 1 file in there "global" here are the contents
```
➜ ~ cat ~/.local/share/flatpak/overrides/global 
[Context]
filesystems=xdg-config/gtk-4.0;xdg-config/gtk-3.0;
```

I do not use any gtk4 themes, here's a screenshot from tweaks as confirmation

![image](https://user-images.githubusercontent.com/35709713/227739388-0e77bb5e-9285-444a-a308-3aa02fc85c77.png)

**Comment by tfuxu** [comment]
Do you maybe have a `/var/lib/flatpak/overrides` folder?

**Comment by IvoryJam** [comment]
I sure do

```
➜ ~ cd /var/lib/flatpak/overrides/
➜ overrides ls
global  org.telegram.desktop
➜ overrides cat global 
[Context]
filesystems=/home/IvoryJam/.themes;/home/IvoryJam/.icons;/home/IvoryJam/.local/share/themes;/home/IvoryJam/.local/share/icons;

[Environment]
GTK_THEME=adw-gtk3
➜ overrides cat org.telegram.desktop 
[Environment]
XCURSOR_SIZE=24
```

**Comment by tfuxu** [comment]
Hmm, remove value from `GTK_THEME` and set `unset-environment=GTK_THEME;` in Context group, this is how I have it on my system and `adw-gtk3` works just fine for Flatpak apps.

**Comment by IvoryJam** [comment]
That fixed it

**Comment by tfuxu** [comment]
One more thing to add to Troubleshooting section

**Comment by daudix-UFO** [comment]
I will start writing troubleshooting docs section!
