### ISSUE TITLE
bug: The preset settings are reset when exiting the user.

### ISSUE THREAD

**Issue by GrafVishna** [GradienceTeam/Gradience#754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The preset settings are reset to the default when exiting the user or restarting the PC. They revert back to the standard preset, and have to be manually changed again after each login.

### To Reproduce

1. I create a color scheme and save it. 2. I apply and use it. 3. I exit the user. 4. I log back in and my preset switches back to the default one.

### Expected behavior

The preset should be applied permanently.

### Screenshots

![2023-04-11_21-29](https://user-images.githubusercontent.com/94762427/231256357-69d4eb2e-eaff-48af-923e-de46d4f3308d.jpg)

### OS

Manjaro Linux

### DE/WM version

GNOME 43.4

### Version

0.4.1-1

### Installation method

Other

### Enabled system extensions (GNOME specific)

gnome-clipboard@b00f.github.io
blur-my-shell@aunetx
widgets@aylur
color-picker@tuberry
appindicatorsupport@rgcjonas.gmail.com
custom-accent-colors@demiskp
dash-to-dock@micxgx.gmail.com
gnome-ui-tune@itstime.tech
legacyschemeautoswitcher@joshimukul29.gmail.com
pamac-updates@manjaro.org
user-theme@gnome-shell-extensions.gcampax.github.com
x11gestures@joseexposito.github.io

### Additional context

Gradience was originally installed from the official Manjaro repository.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix-UFO** [comment]
Please disable the Custom Accent Colors extension, it is known to cause issuea with Gradience

Удачи ;)

**Comment by daudix-UFO** [comment]
@GrafVishna did it help? can I close this issue?

**Comment by GrafVishna** [comment]
Hello! Sorry for the delay in response! Thank you very much! Today, I did as you instructed and uninstalled the extension. Now Gradience is working stable!!! Thank you so much again for your help and the wonderful opportunity to decorate my system!!!

**Comment by daudix-UFO** [comment]
I'm happy this have solved the issue!
