### ISSUE TITLE
feat: typo in readme.md

### ISSUE THREAD

**Issue by dacwatson** [GradienceTeam/Gradience#756]
### Feature description

About the Name

Gradience was originally named Adwaita Manager.

You can see the meaning of Gradience on [Wiktionary](https://en.wiktionary.org/wiki/gradience).

The icon represents: A Paint Roller repainting an Adwaita window, keeping it's functionality.

--------

should be keeping **its** functionality.

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment]
Good catch, thanks!
