### ISSUE TITLE
feat: Move deleted presets to system trash

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#760]
### Feature description

Currently deleting a preset deletes it entirely with only way to restore it is to click "Undo" before the toast are gone, proposal is to move it to system xdg trash instead

### Additional Context

One more step to make Gradience more "Patrick-Star-Proof"

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by tfuxu** [comment]
Do you know if any other app does that? We would need to find a universal API that handles trash operations, so that we won't be limited with this feature to GNOME users with Nautilus installed.

**Comment by daudix-UFO** [comment]
I think trash is universal as freedesktop standard, I will look for other gnome apps that does this

**Comment by daudix-UFO** [comment]
I have looked through some apps and they delete files bypassing trash, sad
