### ISSUE TITLE
feat: Warning icons on colors that are used by adw-gtk3

### ISSUE THREAD

**Issue by lassekongo83** [GradienceTeam/Gradience#762]
### Feature description

Some color values that are used in adw-gtk3 have an icon that says it's not supported.

The following color values are in fact used by adw-gtk3:
`@headerbar_shade_color` (Used for the headerbar bottom border.)
`@card_shade_color` (Used on lists.)
`@dialog_bg_color`
`@dialog_fg_color`

It would be nice if these could be updated.

Gradience version: 0.4.1 flatpak

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by tfuxu** [comment]
Updated in commit 905b314. Thanks for reporting
