### ISSUE TITLE
bug: gradience glitch in the GTK3 apps topbar after applying a theme

### ISSUE THREAD

**Issue by Yisus7u7** [GradienceTeam/Gradience#770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[Grabación de pantalla desde 2023-05-21 16-59-29.webm](https://github.com/GradienceTeam/Gradience/assets/64093255/306e5787-a7b3-4f39-a86e-1893de17d35c)

The bars of any GTK3 application have failures, reproduce an annoying flicker (it cannot be appreciated in the recording, but they really blink annoyingly)

In QT apps the bar is transparent, this error happens in Wayland and X11 equally

![Captura desde 2023-05-21 17-10-39](https://github.com/GradienceTeam/Gradience/assets/64093255/92a0a176-3403-4c35-9747-bcb7d907620b)

### To Reproduce

Apply the theme to GTK3 apps

### OS

Manjaro Linux

### DE/WM version

GNOME Shell 43.5

### Version

0.4.1

### Installation method

AUR

### Enabled system extensions (GNOME specific)

pamac-updates@manjaro.org
user-theme@gnome-shell-extensions.gcampax.github.com
appindicatorsupport@rgcjonas.gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix-UFO** [comment]
This is known issue that happens when using monet engine, it will be fixed in next release, meantime you can remove transparency from `@headerbar_bg_color`

**Comment by Yisus7u7** [comment]
Thanks, How do I remove it? Excuse my ignorance

**Comment by 0xMRTT** [comment]
If your `@headerbar_bg_color` is like `rgba(0, 0, 0, 0.36)`  remove the latest number -> `rgba(0, 0, 0)`
