### ISSUE TITLE
feat: Add shortcuts

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#776]
### Feature description

A shortcuts for opening preferences and displaying apply dialog would be nice to have, as well as help overlay

<kbd>Control</kbd> <kbd>,</kbd> - Open Preferences

<kbd>Control</kbd> <kbd>Return</kbd> - Show Apply Dialog

<kbd>Control</kbd> <kbd>?</kbd> - Show Help Overlay

<kbd>Alt</kbd> <kbd>1 - 3</kbd> - Switch Section

> ![изображение](https://github.com/GradienceTeam/Gradience/assets/77155297/9e139436-c002-4fe6-8464-6fff8d41dbdb)

### Additional Context

A shortcut for opening preset manager would be nice to have too, tho I'm not sure what shortcut is good for this

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by 0xMRTT** [comment]
Gonna add it
