### ISSUE TITLE
track: 0.8.0-beta1

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Gradience#783]
### Feature description

Publish first beta release of 0.8.0

- [x] Add smol release notes
- [x] Create `beta` branch at [Flathub repo](https://github.com/flathub/com.github.GradienceTeam.Gradience)
- [x] Tag release at GitHub
- [x] Add manifest to `beta` with `0.8.0-beta1` tag
- [x] Make our way to TWIG 100
- [x] ~~https://github.com/flathub/flatpak-builder-lint/pull/143~~
- [x] ~~Use dconf hole instead of flatpak spawn~~
- [ ] Check everything one more time
- [ ] Re-tag to include new stuff

### Additional Context

Screenshots for TWIG:

![Снимок экрана от 2023-06-16 13-39-31](https://github.com/GradienceTeam/Gradience/assets/77155297/e9a1653b-525e-454c-bc54-bed7a816dc90)
![Снимок экрана от 2023-06-16 13-38-54](https://github.com/GradienceTeam/Gradience/assets/77155297/0d33cbf3-8ece-4c9f-aa0f-16cbdb4a0525)
![Снимок экрана от 2023-06-16 13-39-10](https://github.com/GradienceTeam/Gradience/assets/77155297/d2d0aa6c-2a34-44b3-b890-367eed17a297)

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by 0xMRTT** [comment]
So we have one day left ...

**Comment by daudix-UFO** [comment]
Hehe :-)

**Comment by LyesSaadi** [comment]
Finally :fire: !

**Comment by daudix-UFO** [comment]
Current announcement text

```
After 4+ months (128 days), We are happy to announce the first beta release of upcoming 0.8.0 release, it adds the most awaited feature; GNOME Shell theming 🎉️ a lot of small UI polishes like added keyboard shortcuts, updated translations and bug fixes. It will be available at Flathub Beta for testing very soon, stay tuned!
```
