### ISSUE TITLE
bug: Conflicts with Amberol

### ISSUE THREAD

**Issue by suwermave** [GradienceTeam/Gradience#786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened!

### To Reproduce

1. Change a theme
2. Open Amberol
3. Open a song that has image cover

### Expected behavior

Theming makes background cover less visible

### OS

Fedora Linux 38 Silverblue

### DE/WM version

GNOME 44.1

### Version

0.4.1

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix-UFO** [comment]
Unfortunately this is side effect of overriding the stylesheet, this is not an issue with Gradience nor Amberol

Amberol uses the window background color to tint the cover, it's just not noticeable because it's either white or grey with default Adwaita
