### ISSUE TITLE
feat: Allow to change Gnome Shell top panel color

### ISSUE THREAD

**Issue by raluvy95** [GradienceTeam/Gradience#798]
### Feature description

Since gnome-shell theme is fully supported by Gradience. One issue is that the gnome shell top panel is always black which doesn't match with other extension such as dash to dock.

I attempted to edit gnome-shell.css directly to change panel color which leaves little black space behind as you can see below
![image](https://github.com/GradienceTeam/Gradience/assets/43247023/c0d1b502-e163-4b1d-856b-f6cef47c888f)

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment]
This is on our roadmap, see https://github.com/GradienceTeam/Gradience/issues/763
