### ISSUE TITLE
bug: Theming issues with panels in gnome shell

### ISSUE THREAD

**Issue by sidevesh** [GradienceTeam/Gradience#801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Opening this to track the issue of panels not getting themed in gnome shell,
https://github.com/GradienceTeam/Gradience/pull/679#issuecomment-1532109838
https://github.com/GradienceTeam/Gradience/pull/679#issuecomment-1532189330

I see support of it was reverted for pre-45 gnome shell versions too because it wasn't working for 44.
https://github.com/GradienceTeam/Gradience/pull/679/commits/611140d63e048dd59536cbd9cd82baf4e7801625

### To Reproduce

Open gnome quick settings
Extend Wi-Fi menu

### OS

Arch Linux

### DE/WM version

GNOME 44

### Version

0.8.0-beta

### Installation method

AUR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix-UFO** [comment]
Thanks, but there already shell theming roadmap https://github.com/GradienceTeam/Gradience/issues/763
