### ISSUE TITLE
bug: Nightly CI build fails

### ISSUE THREAD

**Issue by daudix** [GradienceTeam/Gradience#809]
From Actions logs

![изображение](https://github.com/GradienceTeam/Gradience/assets/77155297/14fb173d-2fb1-4dd4-aee9-1be9456e8fe9)

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by 0xMRTT** [comment]
Why no file or directory lol ? I'll check soon

**Comment by daudix** [comment]
Not a big deal, nightly.link is fine
