### ISSUE TITLE
bug: Gradience Will not apply GTK 4 theme to any apps.

### ISSUE THREAD

**Issue by Its-Juice** [GradienceTeam/Gradience#814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have been trying to troubleshoot gradience for the past few days and nothing has changed. While the shell theme changes accordingly, no apps have ever changed.

### To Reproduce

I have no idea how to reproduce this issue

### OS

Fedora Workstation 38

### DE/WM version

Gnome 44.4

### Version

0.0.8

### Installation method

Flatpak from manual build

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix-UFO** [comment]
Hi, does this occur in version from flathub-beta? have you enabled flatpak theming in gradience preferences?

**Comment by Its-Juice** [comment]
> 

Yes i have enabled app theming. This is a persistent issue on my machine for some reason. I've tried multiple versions and it doesn't want to apply the theme to gtk 4 apps.

**Comment by Its-Juice** [comment]
> 

Yes i have enabled app theming. This is a persistant issue on my machine for some reason. I've tried multiple versions and it doesn't ew

**Comment by 0xMRTT** [comment]
@Its-Juice Can you run `flatpak run com.github.GradienceTeam.Gradience` (add `.Devel` if you used the devel manifest) and send us the logs ?

**Comment by Its-Juice** [comment]
> @Its-Juice Can you run `flatpak run com.github.GradienceTeam.Gradience` (add `.Devel` if you used the devel manifest) and send us the logs ?

nvm somehow it now works. Thanks!
