### ISSUE TITLE
bug: Theming error on nautilus picker window

### ISSUE THREAD

**Issue by K4R7IK** [GradienceTeam/Gradience#815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When applying the theme there are some part of the UI which aren't themed correctly.

### To Reproduce

1. Install Gradience
2. Install adw-gtk3 from AUR.
3. Apply Alpha Tritanopia theme.
4. Try sharing something where you have to select a document with nautilus.

### Expected behavior

Theme should be correct.

### Screenshots

![image](https://github.com/GradienceTeam/Gradience/assets/75395993/af89f135-1d29-48bb-a68f-f7723ca735db)

### OS

Endeavour OS

### DE/WM version

Gnome 44.4

### Version

0.4.1

### Installation method

AUR

### Enabled system extensions (GNOME specific)

user-theme@gnome-shell-extensions.gcampax.github.com
gsconnect@andyholmes.github.io
caffeine@patapon.info
pano@elhan.io
just-perfection-desktop@just-perfection
Vitals@CoreCoding.com
gestureImprovements@gestures
blur-my-shell@aunetx
status-area-horizontal-spacing@mathematical.coffee.gmail.com
supergfxctl-gex@asus-linux.org
openweather-extension@jenslody.de
appindicatorsupport@rgcjonas.gmail.com
top-bar-organizer@julian.gse.jsts.xyz
space-bar@luchrioh
rounded-window-corners@yilozt
color-picker@tuberry

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eboye** [comment]
I can confirm this on Arch

**Comment by SimplyTadpole** [comment]
Can also confirm this on Fedora.

**Comment by 0xMRTT** [comment]
`navigation-sidebar` is the css key for that ... Gonna see what I can do

**Comment by 0xMRTT** [comment]
![image](https://github.com/GradienceTeam/Gradience/assets/105598867/93b5bc4d-6822-473b-a6ff-4b6c723bb3aa)

Fixed

**Comment by 0xMRTT** [comment]
@SimplyTadpole it's fixed in nightly
