### ISSUE TITLE
bug: Gnome Settings, menu not themed

### ISSUE THREAD

**Issue by UnlimitedKaos** [GradienceTeam/Gradience#819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The theme applies to almost everything, the only exception is the menu panel in gnome control center. It uses the standard dark/light theme according to the setting selected.

Im not quite sure when this first started happening, as I dont go into the settings app super often, but I think this is the only thing affected (actually just as Im uploading screenshots Ive noticed that the file selector seems to have a similar issue)

### To Reproduce

1) Install debian and switch to testing
2) Install stable gradience and use the system for a few months without noticing any issues
3) Notice one day that gnome-control-center is choosing to be special
4) Install nightly gradience
5) gnome-control-center is still choosing to be special

### Expected behavior

Panels are consistent with gradience's theme

### Screenshots

Using pretty purple theme:
![Screenshot from 2023-09-07 23-25-23](https://github.com/GradienceTeam/Gradience/assets/80370607/d312b478-df2d-451e-92f7-5c6278423de1)
![Screenshot from 2023-09-07 23-25-32](https://github.com/GradienceTeam/Gradience/assets/80370607/928ae3bb-b284-4906-8d84-605417ae76fd)

file selector:
![Screenshot from 2023-09-07 23-42-34](https://github.com/GradienceTeam/Gradience/assets/80370607/5148b96b-7e84-424e-a44c-5b43ba38aa1a)

### OS

Debian Testing (12)

### DE/WM version

GNOME 44.4

### Version

0.8.0-beta1-36b91fe

### Installation method

Flatpak from Flathub

### Enabled system extensions (GNOME specific)

blur-my-shell@aunetx
screen-rotate@shyzus.github.io
caffeine@patapon.info
dash-to-dock@micxgx.gmail.com
drive-menu@gnome-shell-extensions.gcampax.github.com
launch-new-instance@gnome-shell-extensions.gcampax.github.com
native-window-placement@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
![image](https://github.com/GradienceTeam/Gradience/assets/105598867/72e0ba10-3209-4f1d-8588-450c7c3bb176)

This is already possible... This is just because you haven't set sidebar color :) 

![image](https://github.com/GradienceTeam/Gradience/assets/105598867/50c2eb46-b2d7-49bc-a3a8-aca8afb1a857)

**Comment by UnlimitedKaos** [comment]
Oops, my bad. Everything works normally

**Comment by andresmessina1701** [comment]
@0xMRTT both of those Sidebar options are completely missing from my Gradience app. They just default to Adwaita Dark and I have no GUI way to change them.
