### ISSUE TITLE
bug: Update needed for Geary sidebar

### ISSUE THREAD

**Issue by inthreedee** [GradienceTeam/Gradience#820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When adw-gtk3 was updated to v4.9, the Geary sidebar was displaying the incorrect theme color. I reported this to the adw-gtk3 team here: https://github.com/lassekongo83/adw-gtk3/issues/240

They responded in that issue with this information:

> The value for sidebars are now `sidebar_bg_color`. So add `@define-color sidebar_bg_color your_color`; to `~/.config/gtk-3.0/gtk.css` or wait for a Gradience update to include support for that.

> There's also `sidebar_fg_color`, `sidebar_backdrop_color`, and `sidebar_shade_color`.

### To Reproduce

1. Using adw-gtk3 v4.9 and Gradience v0.4.1, apply a theme (I use Catppuccin Mocha)
2. Launch Geary and note the sidebar is incorrectly colored with the default Adwaita colors.

### Screenshots

Screenshots are in the issue report linked above.

### OS

Arch

### DE/WM version

Gnome

### Version

44.4

### Installation method

AUR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
![image](https://github.com/GradienceTeam/Gradience/assets/105598867/f9aceaba-7dcd-42fc-8e0d-f2f292d52ad4)


Use Gradience Nightly or wait for the release!

**Comment by inthreedee** [comment]
@0xMRTT  Thank you very much!

**Comment by 0xMRTT** [comment]
@inthreedee You're welcome

**Comment by daudix-UFO** [comment]
The adw-gtk3 support warning should be removed from these I guess xD

**Comment by 0xMRTT** [comment]
oh yeah lol
