### ISSUE TITLE
bug: Nothing works under Arch Linux

### ISSUE THREAD

**Issue by aspizu** [GradienceTeam/Gradience#824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

nothing works

### To Reproduce

fix it

### OS

Arch Linux

### DE/WM version

Hyprland

### Version

gradience --version is not a command

### Installation method

AUR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianschelb** [comment]
For sure you do not actually think that anyone can help you based on this problem description

**Comment by 0xMRTT** [comment]
maybe more details about the issue can be helpful indeed

**Comment by ThatOneCalculator** [comment]
I ran into some problems on Arch with it not launching -- `yay -S python-material-color-utilities --overwrite "*"` fixed it for me.

**Comment by hrdkmishra** [comment]
i installed gradience-git via aur and it doesn open at all

**Comment by hrdkmishra** [comment]
> I ran into some problems on Arch with it not launching -- `yay -S python-material-color-utilities --overwrite "*"` fixed it for me.

this wasnt helpful for me

**Comment by hrdkmishra** [comment]
mb everything is fixed after reboot and `yay -S python-material-color-utilities --overwrite "*"` this was helpful

**Comment by hrdkmishra** [comment]
again it aint working no more after adding presets

**Comment by 0xMRTT** [comment]
> again it aint working no more after adding presets

what's not working ?

**Comment by hrdkmishra** [comment]
> what's not working ?

as when i try open the application it just never launches on gnome 45 and even if try to open via terminal i.e _gradience not the cli_ one it just dont show any error it never runs.

i can confirm **flatpak works completely fine** but the arch package aint working

**Comment by 0xMRTT** [comment]
Maybe a packaging issue i'll check

**Comment by ThatOneCalculator** [comment]
I can't reproduce this issue.

**Comment by UnknownCoder56** [comment]
`yay -S python-material-color-utilities --overwrite "*"` fixes it for me, before this the UI was glitching out horribly.

**Comment by UnknownCoder56** [comment]
nvm its back after applying a theme

**Comment by daudix** [comment]
Closing for now, if someone will have this kind of issue again we can reopen it
