### ISSUE TITLE
bug: Flatpak is missing data for gnome shell 45 theming 

### ISSUE THREAD

**Issue by KennyDevT** [GradienceTeam/Gradience#831]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

I opened gradience flatpak through the terminal clicked apply shell theming and it showed me this.

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/gradience/frontend/widgets/shell_theming_group.py", line 113, in on_apply_button_clicked
    user_themes_available = is_shell_ext_installed(ShellTheme().THEME_EXT_NAME)
  File "/app/lib/python3.10/site-packages/gradience/backend/theming/shell.py", line 59, in __init__
    self._detect_shell_version()
  File "/app/lib/python3.10/site-packages/gradience/backend/theming/shell.py", line 278, in _detect_shell_version
    raise UnsupportedShellVersion(
gradience.backend.exceptions.UnsupportedShellVersion: GNOME Shell version 45 is not supported. (Supported versions: 42, 43, 44)

But it works fine in in the aur version.

### To Reproduce

1. Add Flathub beta.
2. Install Gradience beta 0.8.0-beta1
3. Activate Shell Engine
4. Apply Shell Engine

### Expected behavior

Shell Theming should apply.

### OS

Arch Linux

### DE/WM version

GNOME 45.1

### Version

0.8.0-beta1

### Installation method

Flatpak from Github Actions

### Enabled system extensions (GNOME specific)

clipboard-indicator@tudmotu.com
blur-my-shell@aunetx
just-perfection-desktop@just-perfection
dash-to-dock@micxgx.gmail.com
overviewbackground@github.com.orbitcorrection
ding@rastersoft.com
extension-list@tu.berry
drive-menu@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
appindicatorsupport@rgcjonas.gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KennyDevT** [comment]
After compiling from sources it still doesn't work but i managed to get it work from copying the files (Gnome 45 shell theming files) from the .cache of Gnome builder

**Comment by KennyDevT** [comment]
Did This 
sudo cp -r /home/USER/.var/app/org.gnome.Builder/cache/gnome-builder/projects/Gradience/flatpak/staging/x86_64-main/files/share/gradience/shell/45 /var/lib/flatpak/app/com.github.GradienceTeam.Gradience.Devel/current/e435cceae9f3b6db824a2fd37c980f08b8ef97908c4b584ab68a9ffbcb980f46/files/share/gradience/shell

Than This
sudo cp -r /home/USER/.var/app/org.gnome.Builder/cache/gnome-builder/projects/Gradience/flatpak/staging/x86_64-main/files/share/gradience/shell/templates/45 /var/lib/flatpak/app/com.github.GradienceTeam.Gradience.Devel/current/e435cceae9f3b6db824a2fd37c980f08b8ef97908c4b584ab68a9ffbcb980f46/files/share/gradience/shell/templates

**Comment by Akergez** [comment]
any progress there?

**Comment by Arcitec** [comment]
@daudix You can close this ticket. The nightly builds have worked perfectly for weeks. :)
