### ISSUE TITLE
bug: Missing icons

### ISSUE THREAD

**Issue by mvsrgc** [GradienceTeam/Gradience#839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/GradienceTeam/Gradience/assets/14826113/703b6000-5da5-489b-9795-0ed59e5955a6)

Icons were also broken in various places all over my system because Gradience changed the icon theme to Adwaita, which I had to revert back to Yaru.

### To Reproduce

1. Install on Ubuntu 23.10 with Wayland.
2. Install custom color themes from "Discover".
3. Notice missing icon.

### OS

Ubuntu 23.10

### DE/WM version

GNOME  45.1

### Version

0.4.1

### Installation method

Flatpak from Flathub

### Enabled system extensions (GNOME specific)

user@thinkpad:~$ gnome-extensions list --enabled
clipboard-indicator@tudmotu.com
ding@rastersoft.com
tiling-assistant@ubuntu.com
ubuntu-appindicators@ubuntu.com
ubuntu-dock@ubuntu.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix** [comment]
@mvsrgc Is the missing icons provided in the screenshot are the only icons missing in Gradience or there are other ones? if so, can you please screenshot them so I can fix this?

**Comment by daudix** [comment]
Fixed (hopefully) in https://github.com/GradienceTeam/Gradience/commit/0c3ba09d5ece9b7ff024a03622de08078ad282b0
