### ISSUE TITLE
bug: Side bar colour application is broken in Gnome 45

### ISSUE THREAD

**Issue by Stellanora64** [GradienceTeam/Gradience#851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I updated to gnome 45 (fedora 39) and the side bar is no longer applied correctly, and is instead the default Libadwaita dark.

### To Reproduce

Launch the gnome file browser or settings in Gnome 45.

### Expected behavior

The side bar should be coloured correctly.

### Screenshots

![image](https://github.com/GradienceTeam/Gradience/assets/91010433/46d07075-90b7-45c2-8057-2d8b2bea7537)

### OS

Fedora 39

### DE/WM version

Gnome 45.3

### Version

0.4.1

### Installation method

Fedora COPR (lyessaadi/gradience)

### Enabled system extensions (GNOME specific)

appindicatorsupport@rgcjonas.gmail.com
just-perfection-desktop@just-perfection
caffeine@patapon.info
gsconnect@andyholmes.github.io
blur-my-shell@aunetx
gjsosk@vishram1123.com
swap-finger-gestures-3-4@icedman.github.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix** [comment]
This is already fixed in `main` and will be available in the next release. In the meantime you can use latest [development build](https://github.com/GradienceTeam/Gradience/actions/runs/7583555034/artifacts/1180874372), keep in mind that presets aren't updated yet so you'll need to set the missing values manually (sidebar and secondary sidebar)

**Comment by shellheim** [comment]
@daudix I tried to install the latest artifact but couldn't it due it requiring `org.gnome.Platform/x86_64/master`. So this means I have to follow the git version of `org.gnome.Platform` to install gradience-devel? Also, any plans for when the next release is?

**Comment by daudix** [comment]
You need to have a nightly.gnome.org remote enabled for the runtime

As for the release, I'll try doing it this week 😅

**Comment by shellheim** [comment]
Ah, I see. Don't rush the release, take all the time you need, I didn't mean to startle you 😅. Thanks for the awesome app!
