### ISSUE TITLE
bug: error 404 while installing dependencies

### ISSUE THREAD

**Issue by Coderx11** [GradienceTeam/Gradience#853]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

 python-pluggy-1.3.0-1-any is up to date
error: failed retrieving file 'python-pluggy-1.3.0-1-any.pkg.tar.zst' from mirrors.nxtgen.com : The requested URL returned error: 404
error: failed retrieving file 'python-pluggy-1.3.0-1-any.pkg.tar.zst.sig' from mirror.sahil.world : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
 -> error installing repo packages
error installing repo packages
error installing repo packages

### To Reproduce

install with aur or with source code 

### OS

Arch Linux

### DE/WM version

hyprland

### Version

installing 

### Installation method

AUR

### Enabled system extensions (GNOME specific)

 python-pluggy-1.3.0-1-any is up to date
error: failed retrieving file 'python-pluggy-1.3.0-1-any.pkg.tar.zst' from mirrors.nxtgen.com : The requested URL returned error: 404
error: failed retrieving file 'python-pluggy-1.3.0-1-any.pkg.tar.zst.sig' from mirror.sahil.world : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
 -> error installing repo packages
error installing repo packages
error installing repo packages

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Downstream issue, check out AUR connectivity issues
