### ISSUE TITLE
bug: Theme not applying in Ubuntu 23.10

### ISSUE THREAD

**Issue by eudennis** [GradienceTeam/Gradience#856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've installed Gradience from the Flathub store and the adw3-gtk theme already. However, when I apply the colors with Gradience, they don't change - yes, I've tried restarting.

I've searched for some similar issues but didn't find anything related or helpful.

Tried to run the Flatpak app from the terminal, and noticed that when I "Apply", those errors show up - not sure if is related, but it might be:
`F: Not sharing "/usr/share/themes" with sandbox: Path "/usr" is reserved by Flatpak` just after opening and `OSError: [Errno 30] Read-only file system: '/home/d/.var/app/com.github.GradienceTeam.Gradience/config/gtk-4.0/gtk.css'` when tried to apply the color-scheme.

Tried different apps, Nautilus (45.rc), Thunar, Gnome-Terminal, Transmission and Firefox. I haven't seen the color purple color anywhere.

### To Reproduce

1. On Ubuntu 23.10 install Gradience from Flathub
2. Try to apply
3. See no changes :(

### Expected behavior

1. Pretty Purple colors on GTK4 apps and GTK3 apps themed based on adw-gtk3 

### OS

Ubuntu 23.10

### DE/WM version

Gnome 45.2

### Version

0.4.1

### Installation method

Flatpak from Flathub

### Enabled system extensions (GNOME specific)

I've tried to disable all extensions and apply it, didn't work. But either way, here is a quick list:
- Auto Move Window
- Custom Accent Colors
- gTile
- Rounded Window Corners
- User Theme
- Ubuntu AppIndicators

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eudennis** [comment]
I've tried. But now that you've mentioned, when I open the preference view it has this weird behavior below, as it was not saving that preference:

![image](https://github.com/GradienceTeam/Gradience/assets/1117340/0421bb7e-64b2-4ec0-ae50-7d8468c3db41)

**Comment by daudix** [comment]
That's a known libadwaita bug, it's been already fixed in `main`

**Comment by daudix** [comment]
Try manually running these commands and see if theme applies:

```
sudo flatpak override --filesystem=xdg-config/gtk-4.0
```

```
sudo flatpak override --filesystem=xdg-config/gtk-3.0
```

**Comment by daudix** [comment]
For the sidebar theming you can use the nightly, presets aren't updated yet so you'll need setting colors yourself ;)
